### PR TITLE
feat(controller): Support per-output parameter aggregation. Fixes #2393

### LINKED ISSUE #2393: Make aggregated output parameters available by name
# Summary

I'd like to be able to access aggregated output parameters filtered by name. Right now you [can get](https://github.com/argoproj/argo/issues/861) _all_ the output parameters as JSON using `{{steps.STEP-NAME.outputs.parameters}}`. I'd like to add `.PARAM-NAME` to get JSON for _just_ output params by that name.

# Motivation

Someone [asked on StackOverflow](https://stackoverflow.com/q/60569353/684776) how to access aggregated output parameters. They were attempting to access by name like `{{steps.STEP-NAME.outputs.parameters.PARAM-NAME}}`.

That seems intuitive/nice. It would be easy enough to filter using `jq`, but getting the results straight from Argo would be a better UX.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by Ark-kun**
Currently Argo only supports the `{{tasks.<TASKNAME>.outputs.parameters.<NAME>}}` placeholder for the outputs of normal nodes. (For the outputs of the loop nodes there is the `{{tasks.<TASKNAME>.outputs.parameters}}` placeholder, which is replaced with JSON-serialized list of parameter value maps.

This PR adds support for the `{{tasks.<TASKNAME>.outputs.parameters.<NAME>}}` placeholder for the outputs of the loop nodes. The placeholder is replaced with JSON-serialized list of parameter values.

Fixes #2393

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by simster7** [comment]
@Ark-kun please mark this as "Ready for Review" when it's so and I'll take a look

**Comment by alexec** [comment]
@Ark-kun we're going to review some unfinished PRs to determine if we should finish them. Do you plan to continue on this, please?

**Comment by Ark-kun** [comment]
> @Ark-kun we're going to review some unfinished PRs to determine if we should finish them. Do you plan to continue on this, please?

Hello. I think this PR should be ready.
For some reason I'm getting several tests failures in the areas I have not touched.

**Review by simster7 — COMMENTED** [review]
This LGTM. Can we add a test please?

**Comment by Ark-kun** [comment]
> Can we add a test please?

This would be great, but I have not found the tests for the main feature (parameter aggregation), so it looks like this will require non-trivial amount of work.

**Review by simster7 — APPROVED** [review]
I'll add tests for both in a separate PR

**Comment by fvdnabee** [comment]
Will we see this PR released in argo v2.13?

**Pull request merged**
