### PR TITLE
fix(controller): Don't delete created PVC. Fixes #1819

### LINKED ISSUE #1819: PVC goes to "terminating" state on workflow completion.
**Is this a BUG REPORT or FEATURE REQUEST?**:

A bug.

**What happened**:

When workflow having a reference to PersitentVolumeClaim completes the PVC goes to "Terminating" state and stays in this state until the workflow is deleted.

**What you expected to happen**:

PVC should remain intact until the workflow is deleted.

**How to reproduce it (as minimally and precisely as possible)**:

Create workflow with PVC and run it to completion.

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
argo: v2.4.2
  BuildDate: 2019-10-21T18:39:52Z
  GitCommit: 675c66267f0c916de0f233d8101aa0646acb46d4
  GitTreeState: clean
  GitTag: v2.4.2
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Other debugging information (if applicable)**:
```
> argo list
NAME                  STATUS      AGE   DURATION   PRIORITY
october-run-2-c2lv9   Succeeded   6d    2d         0
> kubectl get pvc
NAME                       STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
october-run-2-c2lv9-work   Terminating   pvc-34ad9688-14af-4b9e-adef-75c0b31f7641   500Gi      RWX            nfs            6d12h
```

### PR DESCRIPTION
**Pull request by jamhed**
Motivation:
PVC's are owned by Workflow, and should be deleted together with Workflow.

bug: https://github.com/argoproj/argo/issues/1819

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to USERS.md.

### CODE REVIEW

**Comment by alexec** [comment]
The code you've deleted looks intentional. 

Instead, could there be a configuration option to keep the PVC around?

Alex

**Comment by jamhed** [comment]
@alexec, I can add a switch, but I'd like to understand the use case. At the moment pvc are not deleted on error, and argo tries (and fails) to delete them on wf successful completion only. In any case pvc would be deleted together with workflow object itself (as wf is set to be an owner for them).

**Comment by alexec** [comment]
@jamhed if you want to find out - would it be best to check the Git log and see who made the change maybe?

**Comment by jamhed** [comment]
@alexec, good idea. It looks like this:

f83b2620 - Support for volumeClaimTemplates (ephemeral volumes) in workflows (2 years, 6 months ago) jesse@applatix.com

And I can't figure reasoning out of it :-)

Anyhow, my point is that it doesn't work as expected: PVC's are not deleted, but rather go to Terminating state (being owned by Workflow) and stays this way until Workflow is deleted, and behaviour is inconsistent: PVC's are not deleted on error, but on success. And more to that, it's already covered by setting PVC's ownership to Workflow instance (meaning k8s handles the deletion of PVC's itself without extra help).

**Comment by alexec** [comment]
@jessesuen you could please take a look at this change?

**Comment by alexec** [comment]
@jessesuen bump!

**Comment by jamhed** [comment]
@alexec, what are we going to do if he will not reply?

**Comment by alexec** [comment]
@jessesuen bump number 2.

**Comment by alexec** [comment]
@jamhed I've spoken to @jessesuen about this and we would like this feature, but it is a breaking change for existing users. I could result in many expensive PVCs left around by complete workflows that users have yet to delete.

Could we request a GC flag, similar to `spec.podGC` for this?

**Comment by jamhed** [comment]
@alexec, i can add a flag. However, as of now it's a bug: pvcs are not deleted, but transitioned to "Terminating" state, and stays like that until the workflow is deleted. But when the workflow is deleted the object it owns are also deleted, meaning there is no need to explicitly delete pvcs.

So, the question remains -- what is the use case for the current implementation?

**Comment by alexec** [comment]
> I can add a flag. 

Thank you. 

> So, the question remains -- what is the use case for the current implementation?

I'm afraid I'd have to defer to @jessesuen on that. I'm surprised it does not get deleted. I won't have time to investigate for a couple of days. I'll try and understand more then.

**Comment by alexec** [comment]
@jamhed I'm tidying up old PRs - do you still want to pursue?

**Comment by adinhodovic** [comment]
Can a completed workflow release a bound PV so when a cronjob runs and creates a pvc it can reuse the same PV?

**Pull request closed without merging**
