### PR TITLE
fix(controller): keep special characters in json string when use withItems

### PR DESCRIPTION
**Pull request by cocotyty**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

[https://github.com/argoproj/argo/blob/4eaae251d9147b53604481237732bff36a16a91e/workflow/controller/operator.go#L2729](https://github.com/argoproj/argo/blob/4eaae251d9147b53604481237732bff36a16a91e/workflow/controller/operator.go#L2729)

When `WithItems` setting a array of object json, and one json field value  contains a `&` or other char which will  becomes \uxxxx in json, the value in template execute will be wrong!

For example, my command is `curl http://xx/x?a=b&c=d`. it will becomes `curl http://xx/x?a=b\u0026c=d`. 

When generate replaceMap , the value is 
```
fmt.Sprintf("%v", itemVal)
```
 
[https://github.com/argoproj/argo/blob/4eaae251d9147b53604481237732bff36a16a91e/pkg/apis/workflow/v1alpha1/item.go#L67](https://github.com/argoproj/argo/blob/4eaae251d9147b53604481237732bff36a16a91e/pkg/apis/workflow/v1alpha1/item.go#L67)
This must not only remove quote , it must be `unmarshal`.

### CODE REVIEW

**Review by alexec — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
Can you please sign-off your commits for the DCO check?

**Review by alexec — CHANGES_REQUESTED** [review]
Commits need to be signed-off.

**Comment by cocotyty** [comment]
> Commits need to be signed-off.

Done.

**Review by alexec — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
Phew!

**Pull request merged**
