### PR TITLE
docs: Add `mxnavi` USERS.md

### PR DESCRIPTION
**Pull request by wuminsure**
in my  company,it is used by schedul spark batch task

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by wuminsure** [comment]
have signed the CLA.

**Comment by alexec** [comment]
@wuminsure can I ask how to verify your relationship with your org please?

**Review by alexec — CHANGES_REQUESTED** [review]
Requested more info

**Comment by alexec** [comment]
Bump! Close or continue?

**Comment by alexec** [comment]
Closing pending reply from PR creator. Can always re-open.

**Pull request closed without merging**
