### PR TITLE
fix: Ensure that outstanding workflows are only run once

### PR DESCRIPTION
**Pull request by simster7**
Fixes: https://github.com/argoproj/argo/issues/4392

This reverts #4294 and adds additional fixes.

### CODE REVIEW

**Comment by alexec** [comment]
Lets chat about the correct solution to this at stand-up.

**Comment by alexec** [comment]
Let me get this right:

* The fix of the locking contention + patch fix introduced a race condition between `Run` and `runOutstandingWorkflows` that can result in race?

Could we fix that race using `KeyLock` like we do in the normal controller?

**Comment by simster7** [comment]
Not exactly sure, I actually have more curiosity about the CronWorkflow informer... I'm thinking we should add the write-back and the 1 second sleep fall-back that we have in the Workflow informer.

Regardless of this, there was an issue with `runOutstandingWorkflows` calling `Run`, but not returning from the current context, which it should do because after it calls `Run`, the CronWorkflow object will be persisted, and the current context will now be invalid.

**Comment by simster7** [comment]
Closing in favor of https://github.com/argoproj/argo/pull/4440

**Comment by xiaochi-learn** [comment]
> Not exactly sure, I actually have more curiosity about the CronWorkflow informer... I'm thinking we should add the write-back and the 1 second sleep fall-back that we have in the Workflow informer.
> 
> Regardless of this, there was an issue with `runOutstandingWorkflows` calling `Run`, but not returning from the current context, which it should do because after it calls `Run`, the CronWorkflow object will be persisted, and the current context will now be invalid.

I encountered similar problem that cron sometimes executes 2 workflows when parallelism is replace. So, how did you solve this problem?

**Pull request closed without merging**
