### PR TITLE
fix(ui): Reference secrets in EnvVars. Fixes #3973 

### LINKED ISSUE #3973: Server UI shows "undefined" for environment variable populated from a secret
# Summary

When an environment variable is populated from a secret, the server UI shows `undefined` for its value. This is highly confusing because the user's first reaction is that the secret value isn't being correctly passed. This messaging could be improved by showing `secret` or `hidden` or something to that effect, to indicate that the value does exist, but is not displayed.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by aletepe**
Fix & Enhancement for https://github.com/argoproj/argo/issues/3973

Adds icon, secret and secret key reference when environment variable value comes from a kubernetes secret. Hovering over the icon shows an explanatory tooltip.

image

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
Bump! This is draft. Close or continue?

**Comment by aletepe** [comment]
@alexec I'm continuing, sorry it is taking me a while. I've managed to add the Tooltip too!

I'm going to need guidance in regards to adding tests, can't find where the UI tests are nor how to run them.

**Comment by alexec** [comment]
@aletepe this looks fine to me. We do not have tests for UI code. Is this ready for review?

**Comment by aletepe** [comment]
@alexec in that case, yes it is! I'm moving the PR to Ready for review.

The build step CI / UI _Ensure nothing changed_ is failing though (because the UI has changed), and I'm not sure how to address it.

**Comment by alexec** [comment]
Run `yarn lint` to fix the UI.

**Comment by aletepe** [comment]
That did fix the issue, though there are now tests failing (`TestCleanFieldsExclude`). I have checked and they are failing in `master` too.

**Review by alexec — APPROVED** [review]

**Comment by simster7** [comment]
Back-ported to v2.12.0-rc5

**Pull request merged**
