### PR TITLE
go.mod: use version suffix appropriate for tag

### LINKED ISSUE #2602: import latest v2.7.0 argo version in go project
# Summary

How can I import latest argo in go project?

# Motivation

Why do you need to know this, any examples or use cases you could include?
when I want import argo v2.7.0 in my project
```
go get github.com/argoproj/argo@v2.7.0
```
But I got error
```
not found: github.com/argoproj/argo@v2.7.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
How to fix it?

### PR DESCRIPTION
**Pull request by peterbourgon**
If your repo has a tag that Go modules parses as semver (like [v2.11.1](https://github.com/argoproj/argo/releases/tag/v2.11.1)) then the module name in the corresponding go.mod must meet Go modules' expectations, specifically if it is v2 or above it must include a `/vN` version suffix. If you don't do this, your project is essentially unusable by consumers.

The fix I've made to go.mod here is simple, but this isn't the end: you also need to update all your import paths to use the `/v2` suffix as well.

Fixes #2602

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
Can you please look at the failing jobs and fix?

**Comment by CameronAckermanSEL** [comment]
@peterbourgon doesn't this require a bump to v3? otherwise one would run into the problem where v2 resolves to different versions depending on the package manager

**Comment by peterbourgon** [comment]
@alexec 

> Can you please look at the failing jobs and fix?

Sorry, beyond my scope — my intent here is just to show you what needs to happen for the repo to be valid.

—

@CameronAckermanSEL 

> @peterbourgon doesn't this require a bump to v3? otherwise one would run into the problem where v2 resolves to different versions depending on the package manager

I don't think so — if you have a go.mod you're a Go module, and if you're a Go module you shouldn't be using anything other than Go modules to manage your dependencies.

**Comment by CameronAckermanSEL** [comment]
@peterbourgon, this is a fair point, but because this fundamentally changes how others should be consuming this library, it is a breaking change in that respect. It really impacts users importing this library indirectly because depending on the way a library imports this one, it may resolve to inconsistent versions. 

https://github.com/gofrs/uuid/issues/61

**Comment by peterbourgon** [comment]
Hmm, that's not a breaking change in the semver sense, but sure, happy to bump to v3. I'm also making an attempt at the other necessary changes, commit(s) incoming...

**Comment by CameronAckermanSEL** [comment]
FWIW I agree with you that this is not _traditionally_ a semver change.

**Comment by peterbourgon** [comment]
Replaced by #4197

**Pull request closed without merging**
