### PR TITLE
feat(UI): Move Workflow parameters to top of submit

### PR DESCRIPTION
**Pull request by salanki**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the USERS.md.
* [x] I've signed the CLA and required builds are green. 

When uploading a workflow, or submittint a template, it is more likely that one just wants to submit the workflow by simply modifying parameter values. This also makes Workflow / WorkflowTemplate submissisons less scary for users not familiar with the Worklow YAML itself, as they can simply focus on the top part of the screen and ignore the YAML edit box below.

A future improvement could include an option to hide the YAML editor completely from the UI, ie. where one wants to give access to the UI to people who are allowed to manage Workflow execution but not modify Workflows.

I am requesting input on the styling and paddings here, I think it could look a bit better.

This commit was broken out from https://github.com/argoproj/argo/pull/2635

### CODE REVIEW

**Comment by simster7** [comment]
Can you run `make lint`? This should fix the CI

**Comment by salanki** [comment]
Ok, I just linted the frontend, do not understand why there would be a diff in anything else.

**Comment by salanki** [comment]
The failures seem to happen due to not being up to speed with master. I pulled master and built the branch on master right before submitting the PR. Basically one has to race to make sure CI runs before someone pushes updates to deps etc to master.

**Comment by alexec** [comment]
This is approved, but must be in sync with master. As you have disabled edits from maintainers we cannot do this for you I'm afraid.

**Comment by salanki** [comment]
Weird, I have not disabled that nor can I find the usual checkbox to disable/enable it to the right. I just rebased on master.

**Pull request merged**
