### PR TITLE
fix: Linters should error if nothing was validated

### PR DESCRIPTION
**Pull request by simster7**
Fixes: #3002

* Return an error if nothing was validated

* Use `log.Fatal` if there were any errors, returning exit code 1

### CODE REVIEW

**Comment by simster7** [comment]
Testing to be done as part of https://github.com/argoproj/argo/issues/2738

**Comment by simster7** [comment]
I tried writing tests, but I discovered that the CLI is not well-suited for testing at the moment since it is dependent on setting up the API clients:

```
ctx, apiClient := client.NewAPIClient()
serviceClient := apiClient.NewWorkflowServiceClient()
namespace := client.Namespace()
```

This operation fails on the CI with the error `"invalid configuration: no configuration has been provided"` since it is not configured to host a kube client.

Do you have any suggestions?

It seems to me that to test correctly we would require a larger refactor which @sarabala1979 seems to be working on at #2738.

**Comment by alexec** [comment]
e2e tests?

**Comment by simster7** [comment]
> e2e tests?

Of course... 🤦‍♂️. There were even some existing lint tests there already.

Added!

**Comment by simster7** [comment]
Back-ported to v2.8.1

**Pull request merged**
