### PR TITLE
Allow output parameters with .value, not only .valueFrom

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/argoproj/argo/issues/1329

This small PR just tweaks the validator to enable a valid user scenario.

Scenario:
Upstream tasks used `{{pod.name}}` in to generate some data storage location (e.g. a BigTable table).
Downstream component wants to know the `{{pod.name}}` of upstream.

Currently doing this requires explicitly writing the pod name to file and then telling Argo to pick it up.

This can be made simple by just allowing output parameters with explicitly set `value` (instead of `valueFrom`). This only requires a small validator change so that it does not return error when `.valueFrom` is missing, but `.value` is specified.

Example:

Template that does not output pod name:

```
container:
    command: [myprog.py, arg1, arg2, arg3]
```

Template that outputs pod name (current workaround):

```
container:
    command: [sh, -c, 'echo "{{pod.name}}" > /tmp/pod_name.txt && "$*"',
        myprog.py, arg1, arg2, arg3
    ]
outputs:
    parameters:
    - name: pod-name
      valueFrom:
          path: /tmp/pod_name.txt
```

Template that outputs pod name (after this PR):

```
container:
    command: [myprog.py, arg1, arg2, arg3]
outputs:
    parameters:
    - name: pod-name
      value: "{{pod.name}}"
```

The workaround might not be even possible in cases where we do not know the `command` of the container and cannot inject anything there.

### CODE REVIEW

**Comment by Ark-kun** [comment]
@xianlubird does this look good?

**Comment by xianlubird** [comment]
Seems LGTM.
Pls @sarabala1979 take a look

**Comment by Ark-kun** [comment]
@jessesuen, can you please take a look when you have time? This PR is a small validator-only change.

**Comment by Ark-kun** [comment]
Gentle ping

**Comment by Ark-kun** [comment]
@sarabala1979 @jessesuen Can you please take a look?

**Comment by Downchuck** [comment]
@Ark-kun The work-around (before this patch) doesn't give the desired results for pod.name when running in a task group pod from withParam. My guess is that this patch actually gives the desired results. But heads up on that anyway.

**Pull request merged**
