### PR TITLE
Add workflow node pending status for imagePullError issue

### PR DESCRIPTION
**Pull request by xianlubird**
In many cases,  when user set the error image address or image does not exists. Kubernetes will report  `ImagePullBackOff` as the pod's status. But argo will think this workflow is running and node is health.   If the job will cost much time, when user find that image address is wrong, maybe 10 hours have been cost.  

Argo should report that `ImagePullBackOff` is the failed workflow. So user can find this issue quickly, fix it and won't waste much time.

```
[root@iZbp1flqunhs6fp1b9pe8pZ arg-example]# argo get steps-jxggl
Name:                steps-jxggl
Namespace:           default
ServiceAccount:      default
Status:              Failed
Message:             child 'steps-jxggl-1508661637' failed
Created:             Mon Aug 13 18:17:51 +0800 (10 minutes ago)
Started:             Mon Aug 13 18:17:51 +0800 (10 minutes ago)
Finished:            Mon Aug 13 18:17:57 +0800 (10 minutes ago)
Duration:            6 seconds

STEP            PODNAME                 DURATION  MESSAGE
 ✖ steps-jxggl                                    child 'steps-jxggl-1508661637' failed
 └---✖ hello0   steps-jxggl-1508661637  5s        Back-off pulling image "ttdocker/whalesay"
[root@iZbp1flqunhs6fp1b9pe8pZ arg-example]# kubectl get pods
NAME                     READY     STATUS             RESTARTS   AGE
batchrelease-test-0      1/1       Running            0          6d
batchrelease-test-1      1/1       Running            0          6d
batchrelease-test-2      1/1       Running            0          6d
batchrelease-test-3      1/1       Running            0          6d
steps-jxggl-1508661637   0/2       ImagePullBackOff   0          1h
```

This PR will report image pull error event and set the workflow to failed status.   User can find the issue easily by just run `argo get` command.

### CODE REVIEW

**Comment by jessesuen** [comment]
@xianlubird we actually intend to solve this in another way. Argo will be introducing a new `Pending` phase to show pods which are not yet Running. Today, the nodes transition directly into Running, which masks the underlying issue.

I think failing workflows because of ImagePullBackoff is not totally the desired behavior because this is something that can be corrected *after* the workflow has already started (e.g. by pushing the missing image).

Instead of failing a workflow, the plan is to expose the pods as Pending, and indicate in the Message field any error conditions of the pod (e.g. ImagePullBackOff).

**Comment by xianlubird** [comment]
@jessesuen I have already changed my code according to your comments. When `ImagePullBackOff ` occurs, `argo get` command will return these message below.

```
[root@iZbp1flqunhs6fp1b9pe8pZ arg-example]# argo get steps-c49hk
Name:                steps-c49hk
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Tue Aug 14 11:25:32 +0800 (42 minutes ago)
Started:             Tue Aug 14 11:25:32 +0800 (42 minutes ago)
Duration:            42 minutes 27 seconds

STEP            PODNAME                 DURATION  MESSAGE
 ● steps-c49hk
 └--- hello0             steps-c49hk-2917862106  42m       Back-off pulling image "ttdocker/whalesay" reason ImagePullBackOff
```

```
[root@iZbp1flqunhs6fp1b9pe8pZ arg-example]# kubectl get pods
NAME                     READY     STATUS             RESTARTS   AGE
batchrelease-test-0      1/1       Running            0          6d
batchrelease-test-1      1/1       Running            0          6d
batchrelease-test-2      1/1       Running            0          6d
batchrelease-test-3      1/1       Running            0          6d
steps-c49hk-2917862106   0/2       ImagePullBackOff   0          32m
```

The workflow is also running and node is pending.

**Comment by xianlubird** [comment]
@jessesuen Thanks for your review.  It seems have much more things to do for the new `Pending` status.  It's a better choice to complete this task by you.  I will find some other issue to do, thank you very much :-) .

**Comment by jessesuen** [comment]
Implemented in 09f0591205ec81b4ec03f0f5c534a13648346f41. Closing PR

**Pull request closed without merging**
