### PR TITLE
feat(ui): Add parameter value enum support to the UI. Fixes #4192

### LINKED ISSUE #4192: Provide enum type parameters for Argo workflows
# Summary
This is an enhancement to provide choice parameters as provided by Jenkins
Jenkins Example:
```
choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
```

A similar input parameter type could be provided for workflows. Something in the lines of
```
arguments:
    parameters:
    - name: choice
      defaultValue: one
      valueFrom:
           choices:
               - one
               - two
               - three
```
# Use Cases

When would you use this?

Anyone who is submitting a workflow template from UI, would be able to specify arguments from the dropdown which has values from the `choices` array

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by basanthjenuhb**
Feature: Add UI support for enums
Discussed in https://github.com/argoproj/argo/issues/4192

Signed-off-by: basanthjenuhb <basanthjenuhb@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
@basanthjenuhb looks good from source code. Can you please add a screenshot?

**Comment by alexec** [comment]
@basanthjenuhb - do you plan to continue working on this, please?

**Comment by alexec** [comment]
Slacked @basanthjenuhb asking if he plans to finish this.

**Comment by basanthjenuhb** [comment]
yes, @alexec , finishing it today

**Comment by basanthjenuhb** [comment]
@alexec build failing in e2e tests
`stat: cannot stat '/etc/rancher/k3s/k3s.yaml': No such file or directory`
can you please help in fixing this

**Comment by basanthjenuhb** [comment]
Screenshot 2020-12-05 at 8 56 17 AM
Screenshot 2020-12-05 at 8 56 27 AM

Choosing `two` in the dropdown

Screenshot 2020-12-05 at 8 56 42 AM

@alexec Added screenshots

**Comment by basanthjenuhb** [comment]
@alexec Builds are green again, we can go ahead with this pr

**Review by alexec — APPROVED** [review]

**Pull request merged**
