### PR TITLE
docs: Add Couler, SQLFlow, and Kubeflow to USERS.md

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
do we need a separate section for tools to users? @edlee2121 @Ark-kun @jessesuen ?

**Comment by terrytangyuan** [comment]
My two cents: these are all vendor-neutral open source organizations (although Couler is still young and we haven't open sourced everything eyt) so it might make sense to include in USERS.

**Comment by edlee2121** [comment]
@alexc May be we should call it "Projects Using Argo".
I like the idea of having a separate section for projects so they don't get lost with the much larger section of companies using Argo.

**Comment by terrytangyuan** [comment]
"Projects Using Argo" sounds good to me. Would you like me to add that new section in this PR and then include the three projects in that section?

**Comment by alexec** [comment]
ok - please do that!

**Comment by terrytangyuan** [comment]
Added. Please take another look. @alexec

**Review by alexec — APPROVED** [review]

**Pull request merged**
