### PR TITLE
feat: Add task/step level override of retryStrategy

### PR DESCRIPTION
**Pull request by simster7**
Closes: #2749

### CODE REVIEW

**Comment by simster7** [comment]
Codegen CI blocked by https://github.com/argoproj/argo/issues/2892

**Comment by simster7** [comment]
> I'd like @jessesuen and @sarabala1979 to review this. Can we slather the code with tests please?

We're freezing this PR for now as we haven't yet agreed it's desired at all.

**Comment by sarabala1979** [comment]
@simster7 It is a good feature to pass the custom values to a common template. I  would suggest having templatepatchJSON which will be JSON string get all template elements and apply in the targeted template instead of the only RetryStrategy. 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-override-
  labels:
    argo-e2e: true
spec:
  entrypoint: steps
  templates:
    - name: steps
      dag:
        tasks:
          - name: fail-0-retry
            template: fail
            templatePatch: '{"retryStrategy":{ "limit": "0"}}'
          - name: fail-1-retry
            template: fail
          - name: fail-2-retry
            template: fail

    - name: fail
      container:
        image: alpine
        command: [sh, -c]
        args: ["exit 1"]
```
We can patch all template fields.

**Comment by simster7** [comment]
@sarabala1979 Interesting solution... let's discuss today with the team

**Comment by simster7** [comment]
We have decided to ice-box this feature. Closing for now

**Pull request closed without merging**
