### PR TITLE
fix(server): Update manifests to figure "Unable to retry workflow".

### PR DESCRIPTION
**Pull request by EDGsheryl**
Relate to PR [#2409 ](https://github.com/argoproj/argo/pull/2409)

Signed-off-by: EDGsheryl <edgsheryl@gmail.com>

Checklist:

* [x] this is a bug fix
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the USERS.md.
* [x] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by alexec** [comment]
Sorry - we don't merge into the release branch - you must create a PR with master as the base.

**Comment by alexec** [comment]
I'd like to back-port this to v2.6, so it'd be great to get the PR corrected.

**Comment by alexec** [comment]
Closing as back-ported other PR.

**Comment by EDGsheryl** [comment]
Oh, sorry. I am a noob of git-flow, so maybe I misunderstand what you mean.

**Pull request closed without merging**
