### PR TITLE
docs: added Ramboll Shair to the official users

### PR DESCRIPTION
**Pull request by mdvorakramboll**
added Ramboll Shair to the official users

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by alexec** [comment]
Thank @mdvorakramboll - any chance you can show how you're linked to Ramboll Shair please?

**Comment by mdvorakramboll** [comment]
@alexec I'm listed as a team member on the Ramboll Shair LinkedIn company page: https://www.linkedin.com/company/ramboll-shair/
image

Is that sufficient?

**Comment by alexec** [comment]
> @alexec I'm listed as a team member on the Ramboll Shair LinkedIn company page:

Thank you - I can't figure out which of the employees you are based on your Github profile - can you point yourself out?

**Comment by mdvorakramboll** [comment]
I'm Mike Dvorak, Engineering Manager. Argo is listed in my LinkedIn profile at Ramboll Shair, if you can possibly see that on the public version of my profile. https://www.linkedin.com/in/mike-dvorak/

**Comment by mdvorakramboll** [comment]
Here's my profile that lists us using Argo:
image

**Pull request merged**
