### PR TITLE
Add name prefix filter in list args

### LINKED ISSUE #1577: Filter workflows on name prefix
**Is this a BUG REPORT or FEATURE REQUEST?**: MINOR FEATURE REQUEST

I would like to be able to filter `argo list` by a prefix of the name. The most common use case would be filtering on runs of a given workflow (with a unique generateName).

Of course, this can also be done with `argo list -o name` and standard command line processing tools, so it's not that important, but would also probably be fairly easy.

Related (and more important): https://github.com/argoproj/argo/issues/802

### PR DESCRIPTION
**Pull request by xiechengsheng**
Add name prefix filter in list args. Fixes #1577 
```sh
$ argo list --name-prefix loops-maps-
NAME               STATUS      AGE   DURATION   PRIORITY
loops-maps-6qlzm   Succeeded   1h    26s        0
```

### CODE REVIEW

**Comment by xianlubird** [comment]
What's the difference between `argo list | grep xxx` and this function ?

**Comment by xiechengsheng** [comment]
Maybe the `grep` shows all the results that include the "xxx" string but this only shows the results that start with the prefix. 😅

**Comment by dtaniwaki** [comment]
Maybe, `argo list | egrep "^xxx"` is enough?

**Comment by xiechengsheng** [comment]
@dtaniwaki Of course you are right. I think the strong regex could help us filter any other results that we needed. e.g. "grep Succeeded" could help filter the successed status workflow~ 😅😅

**Pull request closed without merging**
