### PR TITLE
feat(ui): Add Alibaba Cloud OSS related models in UI

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@simster7 Are other artifact types (e.g. S3, etc.) in `models/workflows.ts` being used anywhere? I was thinking adding OSS related types for consistency but if none of them are being used right now perhaps I can remove all of them in this PR?

**Comment by terrytangyuan** [comment]
@simster7 Thanks for confirming. What do you mean by having trouble with CI? Do you mean the status is hanging in "expected"?

**Comment by simster7** [comment]
> Do you mean the status is hanging in "expected"?

Exactly that, it doesn't seem to be happening on other PRs

**Comment by simster7** [comment]
I'll look into it

**Comment by terrytangyuan** [comment]
@simster7 Looks like things are building. Did you find out the issue with my PRs in the CI?

**Comment by simster7** [comment]
I just merged with master

**Pull request merged**
