### PR TITLE
feat: Support Bash Completions for More Resources

### PR DESCRIPTION
**Pull request by dtaniwaki**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

I added more bash completions so we can easily use `WorkflowTemplate`, `ClusterWorkflowTemplate`, and `CronWorkflow`.

### CODE REVIEW

**Comment by alexec** [comment]
@dtaniwaki I thought we could generate this file?

**Comment by dtaniwaki** [comment]
Oh, really? I don't know how to do that.

**Comment by alexec** [comment]
https://www.bookstack.cn/read/cobra/bash_completions.md would it be worthwhile going 10x on this?

**Comment by dtaniwaki** [comment]
@alexec I think that works for subcommands, but not for resource names.

**Pull request merged**
