### PR TITLE
fix(executor): Change the main or wait container resource to get from controller from reference to copy by value

### PR DESCRIPTION
**Pull request by merlintang**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Review by simster7 — DISMISSED** [review]
Can you please explain why this change is necessary and fix the compilation issues?

**Comment by merlintang** [comment]
Hi @simster7 thanks for your review. 

We found this issue since we need to change the wait container resource for specific cases. In this case, the main container and wait container would refer to the same controller resource config, if we change the wait container resource, then the main container would be rewrote by the current way. 

I would fix the compilation issue. thanks again for looking at this.

**Comment by simster7** [comment]
Ok, this LGTM. Please fix compilation issues first

**Review by alexec — APPROVED** [review]

**Review by alexec — CHANGES_REQUESTED** [review]
Please sign at least one commit to pass DCO check.

**Comment by simster7** [comment]
@merlintang Any update on this?

**Comment by simster7** [comment]
Will close this due to inactivity. Feel free to ping me to reopen

**Pull request closed without merging**
