### PR TITLE
fix(executor): race condition in docker kill. Fixes #3053

### LINKED ISSUE #3053: bug: `argoexec` sometimes panics when waiting for a docker:dind sidecar to exit
**What happened**:

There appears to be a Go panic in `argoexec` when the `wait` container terminates a heavily-used `docker:dind` side-car. It happens a lot to me, but not **every** time.

**What you expected to happen**:

`argoexec` should ideally not panic; but at least it should log it.

**How to reproduce it (as minimally and precisely as possible)**:

Still trying to get a minimal test-case I can share, but see below for the use-case.
Reproducing this is difficult, since it requires a special setup and it happens somewhat reliably but it doesn't reproduce 100% of the time.

Here is an example of the workflow template with identifying information removed.

[workflow.yaml](https://github.com/argoproj/argo/files/4645894/example-workflow.yaml.txt)

**Anything else we need to know?**:

For some background — I’m using `docker:dind` and [KinD](https://kind.sigs.k8s.io/) to spin up a k8s cluster to perform integration tests on our custom k8s controllers. After the tests run, my otherwise successful workflow will often-times get marked as an Error with `failed to save outputs: verify serviceaccount argo:default has necessary privileges`. However, the job has no outputs to save, and the `argo:default` service account has a rolebinding `ClusterRole/admin`.

Looking a bit further into the issue, when it happens; the `wait` container terminates with `"exitCode": 2`:

```json
    {
      "containerID": "docker://4dbbbe3e7431a4fa53c109cd9e197fb7ac25aa17978c32b2619ee85edda9bf30",
      "image": "argoproj/argoexec:v2.8.0",
      "imageID": "docker-pullable://argoproj/argoexec@sha256:9eb71f2dae8405d8c053d5beccce15ecf179448ad0809d9f55f1333bf1d71a01",
      "lastState": {},
      "name": "wait",
      "ready": false,
      "restartCount": 0,
      "state": {
        "terminated": {
          "containerID": "docker://4dbbbe3e7431a4fa53c109cd9e197fb7ac25aa17978c32b2619ee85edda9bf30",
          "exitCode": 2,
          "finishedAt": "2020-05-18T17:49:17Z",
          "reason": "Error",
          "startedAt": "2020-05-18T17:31:52Z"
        }
      }
    }
```

As far as I can tell, there is no code in Argo that explicitly exits with this code; however, there is documentation in the [Go runtime Package](https://golang.org/pkg/runtime/):

> By default, a failure prints a stack trace for the current goroutine, eliding functions internal to the run-time system, and then exits with exit code 2.

Unfortunately, there is no stacktrace to be found in the wait log, so something seems to be hiding it; but it seems to happen after `[docker wait {ID}]`

In the rare cases where the issue does not reproduce, the `wait` container yields some additional logs past the `[docker wait {ID}]` message, indicating that it successfully ran the docker wait command:

```plain_text
time="2020-05-16T00:33:18Z" level=info msg="Main container completed"
time="2020-05-16T00:33:18Z" level=info msg="No output parameters"
time="2020-05-16T00:33:18Z" level=info msg="No output artifacts"
time="2020-05-16T00:33:18Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-05-16T00:33:18Z" level=info msg="Capturing script exit code"
time="2020-05-16T00:33:18Z" level=info msg="[docker inspect 2f929e8444e9f9405b3e05b8fb484f769c2abf227dd24667e980c04829b89dc1 --format='{{.State.ExitCode}}']"
time="2020-05-16T00:33:18Z" level=info msg="Containers [2f929e8444e9f9405b3e05b8fb484f769c2abf227dd24667e980c04829b89dc1] killed successfully"
time="2020-05-16T00:33:18Z" level=info msg="Annotating pod with output"
time="2020-05-16T00:33:18Z" level=info msg="Killing sidecars"
time="2020-05-16T00:33:18Z" level=info msg="Killing sidecar docker-daemon (a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc)"
time="2020-05-16T00:33:18Z" level=info msg="docker kill --signal TERM a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc"
time="2020-05-16T00:33:18Z" level=info msg="[docker wait a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc]"
------------- This is where the logging would stop in the "Error" case -------------
time="2020-05-16T00:33:20Z" level=info msg="Containers [a390618204fa2f59352e1ebf896652824617b8e8a5c4bc2450c98a764cc880dc] killed successfully"
time="2020-05-16T00:33:20Z" level=info msg="Alloc=5968 TotalAlloc=12210 Sys=71104 NumGC=4 Goroutines=9"
```

I was able to work around this issue by running 

```shell
docker ps --format="{{ .ID }}" | xargs docker kill
docker ps -a --format="{{ .ID }}" | xargs docker rm
```

In my main container before exiting. I suspect only the `docker kill` one is necessary though.

**Environment**:

* Argo version:

    ```shell
    $ argo version
    argo: v2.8.0
    BuildDate: 2020-05-11T22:55:16Z
    GitCommit: 8f696174746ed01b9bf1941ad03da62d312df641
    GitTreeState: clean
    GitTag: v2.8.0
    GoVersion: go1.13.4
    Compiler: gc
    Platform: linux/amd64
    ```

* Kubernetes version :

    ```shell
    $ kubectl version -o yaml
    clientVersion:
    buildDate: "2019-12-07T21:20:10Z"
    compiler: gc
    gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
    gitTreeState: clean
    gitVersion: v1.17.0
    goVersion: go1.13.4
    major: "1"
    minor: "17"
    platform: linux/amd64
    ```

**Other debugging information (if applicable)**:

* workflow result:

    ```shell
    $ argo --loglevel DEBUG get docker-kind-tester-2nvpp
    Name:                docker-kind-tester-2nvpp
    Namespace:           argo
    ServiceAccount:      default
    Status:              Error
    Message:             failed to save outputs: verify serviceaccount argo:default has necessary privileges
    Created:             Mon May 18 17:31:47 +0000 (17 minutes ago)
    Started:             Mon May 18 17:31:47 +0000 (17 minutes ago)
    Finished:            Mon May 18 17:49:29 +0000 (12 seconds ago)
    Duration:            17 minutes 42 seconds

    STEP                          TEMPLATE  PODNAME                    DURATION  MESSAGE
    ⚠ docker-kind-tester-2nvpp  tester    docker-kind-tester-2nvpp  17m       failed to save outputs: verify serviceaccount argo:default has necessary privileges
    ```

**Logs**

* [workflow-controller.log](https://github.com/argoproj/argo/files/4645886/workflow-controller.log)
* [wait.log](https://github.com/argoproj/argo/files/4645887/wait.log)
* [init.log](https://github.com/argoproj/argo/files/4645889/init.log)
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by justenwalker**
Fix a race condition caused by setting err in DockerExecutor.Kill concurrently from both the main goroutine and the forceKill goroutine.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, **(b) this is a bug fix**, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] ~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] ~My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).~

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
@justenwalker how have you tested this changes please?

**Comment by justenwalker** [comment]
> @justenwalker how have you tested this changes please?

I mostly tested it indirectly.

- I know it's a race because the code it replaces follows the same pattern as this toy example I made to illustrate the problem in #3053: https://play.golang.org/p/HLpYgX9ALkP (see https://github.com/argoproj/argo/issues/3053#issuecomment-631239885)
  Run it with `go run -race ./HLpYgX9ALkP.go` to see the data race identified.
- The proposed fix has the desired behavior for all the failure modes without the race, since it's the same as:  https://play.golang.org/p/MfosAR4YUus and this code can be validated race-free with `go run -race ./MfosAR4YUus.go`
- The change is hopefully small enough to be visually inspected for correctness
- I'm also assuming the e2e tests that run on the PR would suffice to ensure that this change does not introduce regressions in other areas.

However, I have not tested it directly - as in I do not have a minimally reproducible, failing test-case that this PR will make pass.

*Note*: Since this is a race condition, it's difficult *in general* to reproduce reliably. Even when I reported #3053, I tried to get a minimally reproducible test-case to no avail. It wasn't reliably reproducible in production either (but happened often enough to be annoying, since it invalidated around 30mins of work each time it occurred). 

None of that is a particularly satisfying answer, I know... but it's where I'm at.

If that is not sufficient, what sort of test would you accept?

**Comment by alexec** [comment]
@justenwalker can you please be available to fix any issues we might find?

**Comment by justenwalker** [comment]
> @justenwalker can you please be available to fix any issues we might find?

Sure. I'll do my best. Worst case, you can revert this PR and it will resume with the previous (albeit, still broken) behavior.

**Pull request merged**
