### PR TITLE
feat(ui): Make attributes rows easier to read

### PR DESCRIPTION
**Pull request by simonfrey**
Closes https://github.com/argoproj/argo/issues/4337

If you are happy with the change please add the `hacktoberfest-accepted` label to the PR. (See [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update))

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Review by simster7 — COMMENTED** [review]
Can you send a before/after screenshot please?

Also, can you link a documentation for `columns--narrower-height`? I can't seem to find some after a 5 second google search 🙂

**Comment by simster7** [comment]
@simonfrey Bump. Are you still interested in merging this?

**Comment by simonfrey** [comment]
Jepp still interested ;) 

---

The --narrow-height is from the ui-lib: https://github.com/argoproj/ui-lib/blob/master/src/assets/styles/elements/_containers.scss#L66-L70

---

Before: before
After: after

**Review by simster7 — APPROVED** [review]
Thanks @simonfrey!

**Comment by alexec** [comment]
Bump! Close or continue?

**Comment by alexec** [comment]
Just a reminder - we cannot accept PRs where the commits have not been signed with the DCO.

**Pull request merged**
