### PR TITLE
fix(argo-server): fix global variable validation error with reversed dag.tasks. Fixes #4273

### LINKED ISSUE #4273: [Bug] Global output parameters validation error with reversed dag.tasks order
## Summary 

What happened/what you expected to happen?

A workflow using global output parameter and DAG could work well with Argo, but if I reverse the dag.tasks list, argo server would return a global output parameters validation error like:
```
{
    "code": 2,
    "message": "templates.dag.tasks.second templates.second: failed to resolve {{workflow.outputs.parameters.first-global-name}}"
}
```

Expection:
Parameter verification should not be related to DAG tasks' order.

## Diagnostics

What Kubernetes provider are you using? 

Bare-metal v1.13.12

What version of Argo Workflows are you running? 

v2.11.3

The workflow works well:
```
POST {argo-server}/api/v1/workflows/test4
{
    "namespace":"test4",
    "workflow":{
        "metadata":{
            "name":"workflow-works-well",
            "namespace":"test4"
        },
        "spec":{
            "templates":[
                {
                    "name":"dag",
                    "dag":{
                        "tasks":[
                            {
                                "name":"first",
                                "template":"first"
                            },
                            {
                                "name":"second",
                                "template":"second",
                                "dependencies":[
                                    "first"
                                ]
                            }
                        ]
                    }
                },
                {
                    "name":"first",
                    "container":{
                        "name":"test",
                        "image":"ubuntu",
                        "command":[
                            "sh",
                            "-c",
                            "echo first > /tmp/empty-dir/output.txt"
                        ],
                        "volumeMounts":[
                            {
                                "mountPath":"/tmp/empty-dir",
                                "name":"output"
                            }
                        ]
                    },
                    "outputs":{
                        "parameters":[
                            {
                                "name":"first-output",
                                "valueFrom":{
                                    "path":"/tmp/empty-dir/output.txt"
                                },
                                "globalName":"first-global-name"
                            }
                        ]
                    },
                    "volumes":[
                        {
                            "name":"output",
                            "emptyDir":{

                            }
                        }
                    ]
                },
                {
                    "name":"second",
                    "container":{
                        "name":"test",
                        "image":"ubuntu",
                        "command":[
                            "sh",
                            "-c",
                            "echo {{workflow.outputs.parameters.first-global-name}}"
                        ]
                    }
                }
            ],
            "entrypoint":"dag",
            "serviceAccountName":"workflow"
        }
    }
}
```

The workflow suffers from a validation error:
```
POST {argo-server}/api/v1/workflows/test4
{
    "namespace":"test4",
    "workflow":{
        "metadata":{
            "name":"workflow-error",
            "namespace":"test4"
        },
        "spec":{
            "templates":[
                {
                    "name":"dag",
                    "dag":{
                        "tasks":[
                            {
                                "name":"second",
                                "template":"second",
                                "dependencies":[
                                    "first"
                                ]
                            },
                            {
                                "name":"first",
                                "template":"first"
                            }
                        ]
                    }
                },
                {
                    "name":"first",
                    "container":{
                        "name":"test",
                        "image":"ubuntu",
                        "command":[
                            "sh",
                            "-c",
                            "echo first > /tmp/empty-dir/output.txt"
                        ],
                        "volumeMounts":[
                            {
                                "mountPath":"/tmp/empty-dir",
                                "name":"output"
                            }
                        ]
                    },
                    "outputs":{
                        "parameters":[
                            {
                                "name":"first-output",
                                "valueFrom":{
                                    "path":"/tmp/empty-dir/output.txt"
                                },
                                "globalName":"first-global-name"
                            }
                        ]
                    },
                    "volumes":[
                        {
                            "name":"output",
                            "emptyDir":{

                            }
                        }
                    ]
                },
                {
                    "name":"second",
                    "container":{
                        "name":"test",
                        "image":"ubuntu",
                        "command":[
                            "sh",
                            "-c",
                            "echo {{workflow.outputs.parameters.first-global-name}}"
                        ]
                    }
                }
            ],
            "entrypoint":"dag",
            "serviceAccountName":"workflow"
        }
    }
}
```

The only different thing is the order of dag.tasks.

```
Paste the logs from the argo-server:
kubectl logs argo-server-6d5dd8655d-bh9dj -n argo

time="2020-10-14T12:11:04Z" level=error msg="finished unary call with code Unknown" error="templates.dag.tasks.second templates.second: failed to resolve {{workflow.outputs.parameters.first-global-name}}" grpc.code=Unknown grpc.method=CreateWorkflow grpc.service=workflow.WorkflowService grpc.start_time="2020-10-14T12:11:04Z" grpc.time_ms=0.322 span.kind=server system=grpc
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by cy-zheng**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 

Fixes #4273

### CODE REVIEW

**Comment by cy-zheng** [comment]
https://github.com/argoproj/argo/pull/4357 breaks our CI tests.

**Review by simster7 — COMMENTED** [review]
Hi @cy-zheng. Thanks for this great PR and sorry for the delay. Can you confirm this for me: this issue only happens during validation and not during execution, correct? I.e. the ordering of the tasks does not matter at all during execution.

**Comment by cy-zheng** [comment]
> Hi @cy-zheng. Thanks for this great PR and sorry for the delay. Can you confirm this for me: this issue only happens during validation and not during execution, correct? I.e. the ordering of the tasks does not matter at all during execution.

Hi @simster7, sorry for the late response. As I have tested, this issue could also happen in workflow controller side. I got some events from workflow controller:
```
Events:
  Type     Reason           Age   From                 Message
  ----     ------           ----  ----                 -------
  Normal   WorkflowRunning  34s   workflow-controller  Workflow Running
  Warning  WorkflowFailed   34s   workflow-controller  invalid spec: templates.unresolved.tasks.B templates.second: failed to resolve {{workflow.outputs.parameters.global}}
```

**Comment by alexec** [comment]
@simster7 - I think this PR is waiting for your feedback?

**Review by simster7 — APPROVED** [review]
Sorry for the delay. I am ok with having this be a validation-only check for now and revisiting in the future if necessary

**Comment by alexec** [comment]
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4

**Pull request merged**
