### PR TITLE
fix(server): Add `list sa` and `create secret` to `argo-server` roles. Closes #4526

### LINKED ISSUE #4526: sso secretname on configmap is not respected and defaults to sso as secretname
## Summary 

sso secret name on --configmap=argo-workflow-controller-configmap is not respected and defaults to "sso" as the secret name even we define secret on  argo-workflow-controller-configmap configmap. This is working fine on v2.11.17 but not on v2.12.0-rc2

## Diagnostics

AKS 1.16.15

Argo 2.12.0-rc2

Argo-Server pods:

```yaml
kubectl logs -n argowf argo-server-b754b67fc-9qmjw 
time="2020-11-13T14:12:39Z" level=info authModes="[sso]" baseHRef=/workflow/ managedNamespace= namespace=argowf secure=false
time="2020-11-13T14:12:39Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo/tls/"
time="2020-11-13T14:12:39Z" level=info msg="config map" name=argo-workflow-controller-configmap
time="2020-11-13T14:12:40Z" level=fatal msg="failed to read secret: secrets \"sso\" not found"
```

configmap (containing argo-server-sso as sso section)

```yaml
    sso:
      clientId:
        key: client-id
        name: argo-server-sso
      clientSecret:
        key: client-secret
        name: argo-server-sso
      issuer: xxx.com
      redirectUrl: https://xxx.com/workflow/oauth2/callback
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by Boolman**
In 2.12.0-rc1 when using SSO RBAC - argo fails to create the secret, due to missing permissions in the argo-server-role
https://github.com/argoproj/argo/blob/0931baf5fbe48487278b9a6c2fa206ab02406e5b/server/auth/sso/sso.go#L135-L138

### CODE REVIEW

**Comment by Boolman** [comment]
list permission is required on serviceaccounts:

https://github.com/argoproj/argo/blob/bfc13c3f5b9abe2980826dee1283433b7cb22385/server/auth/gatekeeper.go#L167-L171

**Comment by alexec** [comment]
Please run `make codegen` to fix build.

**Comment by alexec** [comment]
I'm not 100% sure we should add `list sa` and `create secret` to `argo-server` role. It is new privileges only needed for SSO + RBAC.

@jessesuen thoughts?

**Review by alexec — APPROVED** [review]
Needs back-porting to v2.12.0-rc3

**Comment by sarabala1979** [comment]
@Boolman Can you fix the codegen and DCO? We are targeting this PR for RC3 release

**Comment by Boolman** [comment]
I dont understand why the codegen fails, it reports no change in my local branch.
And the DCO says: 'Commit sha: af85335, Author: Alex Collins, Committer: GitHub; The sign-off is missing.'

**Comment by jessesuen** [comment]
> I'm not 100% sure we should add list sa and create secret to argo-server role. It is new privileges only needed for SSO + RBAC.

So long as this is in the namespace of the argo-server, I don't see a problem with it

**Comment by alexec** [comment]
This looks good, but it needs either (a) run `make codegen` or (b) apply this patch:

```
diff --git a/manifests/quick-start-minimal.yaml b/manifests/quick-start-minimal.yaml
index f70741e9..5468fc25 100644
--- a/manifests/quick-start-minimal.yaml
+++ b/manifests/quick-start-minimal.yaml
@@ -612,7 +612,8 @@ spec:
         runAsNonRoot: true
       serviceAccountName: argo-server
       volumes:
-      - name: tmp
+      - emptyDir: {}
+        name: tmp
 ---
 apiVersion: apps/v1
 kind: Deployment
diff --git a/manifests/quick-start-mysql.yaml b/manifests/quick-start-mysql.yaml
index ae1b29f1..4021bb39 100644
--- a/manifests/quick-start-mysql.yaml
+++ b/manifests/quick-start-mysql.yaml
@@ -656,7 +656,8 @@ spec:
         runAsNonRoot: true
       serviceAccountName: argo-server
       volumes:
-      - name: tmp
+      - emptyDir: {}
+        name: tmp
 ---
 apiVersion: apps/v1
 kind: Deployment
diff --git a/manifests/quick-start-postgres.yaml b/manifests/quick-start-postgres.yaml
index c77ffede..12688edc 100644
--- a/manifests/quick-start-postgres.yaml
+++ b/manifests/quick-start-postgres.yaml
@@ -656,7 +656,8 @@ spec:
         runAsNonRoot: true
       serviceAccountName: argo-server
       volumes:
-      - name: tmp
+      - emptyDir: {}
+        name: tmp
 ---
 apiVersion: apps/v1
 kind: Deployment
```

**Review by alexec — CHANGES_REQUESTED** [review]
Changes requested

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
LGTM

**Pull request merged**
