### PR TITLE
feat(controller): Support K8S JSON patch with resource template. Closes #4883

### LINKED ISSUE #4883: support K8S json patch
# Summary

Argo template Resource.Action support using patch, which execute `kubectl patch ...` command.

K8S has [three types of patch](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/): strategic merge patch, JSON merge patch and JSON patch. [JSON patch body is an array](https://tools.ietf.org/html/rfc6902), which not support by Argo currently. Because Argo just [unmarshal to `unstructed.Unstructed` for all resource manifest](https://github.com/argoproj/argo/blob/v2.11.7/workflow/validate/validate.go#L701). 

Should use [`jsonpatch.Decode`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/patch/patch.go#L320) for validation when mergeStrategy is json

# Use case

When we want to do merge patch for resource doesn't specify patchStrategy=merge in K8S like RoleBinding.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by book987**
#4883 

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
Failing test
```
   --- FAIL: TestFunctionalSuite/TestK8SJSONPatch (4.45s)
        functional_test.go:1028: 
            	Error Trace:	functional_test.go:1028
            	            				then.go:57
            	            				then.go:32
            	            				functional_test.go:1025
            	Error:      	Not equal: 
            	            	expected: ""
            	            	actual  : "Error from server (Forbidden): error when retrieving current configuration of:\nResource: \"/v1, Resource=serviceaccounts\", GroupVersionKind: \"/v1, Kind=ServiceAccount\"\nName: \"test-sa\", Namespace: \"argo\"\nfrom server for: \"/tmp/manifest.yaml\": serviceaccounts \"test-sa\" is forbidden: User \"system:serviceaccount:argo:default\" cannot get resource \"serviceaccounts\" in API group \"\" in the namespace \"argo\"\nError from server (Forbidden): error when retrieving current configuration of:\nResource: \"rbac.authorization.k8s.io/v1, Resource=roles\", GroupVersionKind: \"rbac.authorization.k8s.io/v1, Kind=Role\"\nName: \"test-role\", Namespace: \"argo\"\nfrom server for: \"/tmp/manifest.yaml\": roles.rbac.authorization.k8s.io \"test-role\" is forbidden: User \"system:serviceaccount:argo:default\" cannot get resource \"roles\" in API group \"rbac.authorization.k8s.io\" in the namespace \"argo\"\nError from server (Forbidden): error when retrieving current configuration of:\nResource: \"rbac.authorization.k8s.io/v1, Resource=rolebindings\", GroupVersionKind: \"rbac.authorization.k8s.io/v1, Kind=RoleBinding\"\nName: \"test-role-binding\", Namespace: \"argo\"\nfrom server for: \"/tmp/manifest.yaml\": rolebindings.rbac.authorization.k8s.io \"test-role-binding\" is forbidden: User \"system:serviceaccount:argo:default\" cannot get resource \"rolebindings\" in API group \"rbac.authorization.k8s.io\" in the namespace \"argo\""
```

I think you need to look at workflow-role.yaml to see what permissions you have. I suggest that you have `pod patch` so maybe change the resource to a pod.

**Comment by book987** [comment]
> I suggest that you have `pod patch` so maybe change the resource to a pod.

It works! Thanks!

**Review by alexec — APPROVED** [review]
LGTM!

**Comment by wreed4** [comment]
:tada: yay merged!

@alexec Out of curiosity, just trying to understand the release Argo Workflows release process, when should I expect to see this make it's way into a released tag?  We're waiting on it to adopt v3.x, but the main reason I'm asking isn't to rush, just to understand.  it's a huge project with so many branches and commits coming in it's mind boggling!

**Comment by terrytangyuan** [comment]
You can see a list of tags in this commit https://github.com/argoproj/argo-workflows/commit/6e961ec928ee35e3ae022826f020c9722ad614d6

**Comment by wreed4** [comment]
perfect thanks @terrytangyuan

**Comment by wreed4** [comment]
ope, I meant to comment on #5951  I'm blind.  But answer applies anyways! Thanks! :)

**Pull request merged**
