### PR TITLE
chore: Deprecate unused RuntimeResolution field

### PR DESCRIPTION
**Pull request by simster7**
Fixes https://github.com/argoproj/argo/issues/4102

### CODE REVIEW

**Comment by simster7** [comment]
@dtaniwaki Care to comment?

**Review by dtaniwaki — APPROVED** [review]
Thank you for taking care of the deprecation. I added the flag to allow users to create or change workflow templates after a workflow submission. e.g. You can create or change them while a workflow is suspended. However, I understand the purpose of the flag is not intuit and made confusion like the linked issue of #4102. Let's deprecate the flag and find a better way to allow that kind of lazy resolution.

**Comment by simster7** [comment]
Thanks for your comments @dtaniwaki

**Comment by endzyme** [comment]
Thanks all, for addressing this

**Pull request merged**
