### PR TITLE
chore: Fix GitHub Actions Docker Image build 

### PR DESCRIPTION
**Pull request by lippertmarkus**
In #3291 I used the Docker username as the organization/repository to push the Docker images to. Organizations on Docker Hub work different as you log-in with your own user but push to the organization repository with a different name than your username. I introduced another secret to address this. You would need to set the following secret to the name of the organization on Docker Hub before merging:

- `DOCKERIO_ORG` = `argoproj`

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by lippertmarkus** [comment]
Seems to work now, thank you! 🎉

**Comment by lippertmarkus** [comment]
@alexec In case you wondered why there was no Docker Image created automatically for v2.9.3: The workflow file `docker-image.yml` must be present on the triggering branch for the workflow to run.
So it will work when creating the next release-2.10 branch based on master (because it then includes this file) or, if you want to make it work for upcoming 2.9.x releases you would need to cherry-pick #3442 and #3291 into the `release-2.9` branch.

**Comment by alexec** [comment]
I've disabled auto-builds.

**Comment by alexec** [comment]
Cherry-picked to v2.9. Will run on v2.9.4 (hopefully).

**Pull request merged**
