### PR TITLE
fix: onExit step gets stuck if the workflow exceeds activeDeadlineSeconds. Fixes #2603

### LINKED ISSUE #2603: onExit step gets stuck if the workflow exceeds activeDeadlineSeconds
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [] I've included the logs.
 
**What happened**:

onExit step gets stuck if the workflow exceed the deadline, and workflow stays in 'Running' state'

**What you expected to happen**:

either onExit step executes or it doesn't.

**How to reproduce it (as minimally and precisely as possible)**:

Submit this workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exit-handlers
spec:
  entrypoint: intentional-fail
  activeDeadlineSeconds: 1
  onExit: exit-handler
  templates:
  - name: intentional-fail
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
  - name: exit-handler
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo send e-mail: {{workflow.name}} {{workflow.status}}."]
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-05T16:54:35Z"
  compiler: gc
  gitCommit: f6278300bebbb750328ac16ee6dd3aa7d3549568
  gitTreeState: clean
  gitVersion: v1.15.2
  goVersion: go1.12.7
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-09-18T14:39:02Z"
  compiler: gc
  gitCommit: 8fca2ec50a6133511b771a11559e24191b1aa2b4
  gitTreeState: clean
  gitVersion: v1.14.7
  goVersion: go1.12.9
  major: "1"
  minor: "14"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:

```
Name:                exit-handlers
Namespace:           staging
ServiceAccount:      default
Status:              Running
Created:             Mon Apr 06 15:11:12 +0100 (1 hour ago)
Started:             Mon Apr 06 15:11:12 +0100 (1 hour ago)
Duration:            1 hour 21 minutes

STEP                                    PODNAME                   DURATION  MESSAGE
 ⚠ exit-handlers (intentional-fail)     exit-handlers             0s        Pod "exit-handlers" is invalid: spec.activeDeadlineSeconds: Invalid value: 0: must be between 1 and 2147483647, inclusive

 ◷ exit-handlers.onExit (exit-handler)  exit-handlers-1117225324  1h
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by mark9white**
Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [X] Optional. I've added My organization is added to the USERS.md.
* [X] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by alexec** [comment]
@simster7 do you want to take a look?

**Comment by simster7** [comment]
> @simster7 do you want to take a look?

Yes, please don't merge until I've had a chance to look

**Comment by mark9white** [comment]
I had a play and if the exit handler runs quickly enough then wfActiveDeadlineSeconds is zero at workflowpod.go:109 in which case I get an error like:
```
Pod "exit-handler-sleep-2733314521" is invalid: spec.activeDeadlineSeconds: Invalid value: 0: must be between 1 and 2147483647, inclusive
```

If at least a second passes before it reaches workflowpod.go:109 then wfActiveDeadlineSeconds is negative and workflowpod.go:110 is triggered.

If we're fine with deadline not applying to onExit, how about we modify it to:
```
	wfDeadline := woc.getWorkflowDeadline()
	if wfDeadline == nil || opts.onExitPod { //ignore the workflow deadline for exit handler so they still run if the deadline has passed
		activeDeadlineSeconds = tmpl.ActiveDeadlineSeconds
	} else {
		wfActiveDeadlineSeconds := int64((*wfDeadline).Sub(time.Now().UTC()).Seconds())
		if wfActiveDeadlineSeconds <= 0 {
			return nil, nil
		} else if tmpl.ActiveDeadlineSeconds == nil || wfActiveDeadlineSeconds < *tmpl.ActiveDeadlineSeconds {
			activeDeadlineSeconds = &wfActiveDeadlineSeconds
		} else {
			activeDeadlineSeconds = tmpl.ActiveDeadlineSeconds
		}
	}
```

**Comment by mark9white** [comment]
Great. My 2 cents is that it should still run, but applying deadlines set
within it.

**Comment by simster7** [comment]
> Great. My 2 cents is that it should still run, but applying deadlines set
within it.

I'll definitely bring this up!

**Comment by mark9white** [comment]
Thinking about the:
```
return nil, nil
```

So this never creates a pod, we end up with a pending node, what would clean up that node? Normally it would be when the pod is iterated by execution control, but as we never created one that doesn't happen ...

**Comment by simster7** [comment]
Hey @mark9white, we are going with the approach where the `onExit` handler still runs after the `activeDeadlineSeconds` is expired.

> Thinking about the:
>     nil, nil

Happens here:

https://github.com/argoproj/argo/blob/8c29e05cb5befe5f9f0263ff138eab66f75c54d0/workflow/controller/operator.go#L783-L799

**Comment by mark9white** [comment]
Great, I've just adjusted this PR so it doesn't time out onExit pods.

The nil, nil results in a Pending node, which I'm afraid the code you pasted skips over in line 790.

**Comment by mark9white** [comment]
I had to trigger build because of a failure in TestCLISuite/TestLogProblems but as far as I can see it was a flake and has no relation to this PR.

So from my pov, this is ready to squash and merge.

**Comment by simster7** [comment]
> The nil, nil results in a Pending node, which I'm afraid the code you pasted skips over in line 790.

Oh you're right... seems to be a fairly recent change: https://github.com/argoproj/argo/pull/2385/files#diff-fcb04129f1d32e69cca32631c6586587R757 that I'd forgotten about. Good to have in mind in case any issues arise

**Comment by simster7** [comment]
Back-ported to 2.7

**Comment by Ark-kun** [comment]
> get feedback on whether `onExit` should run after `activeDeadlineSeconds` has passed.

We had feedback from our users that they're surprised that onExit handlers do not run when Workflow is terminated. onExit handlers usually has cleanup routines (cluster deletion, etc).

**Comment by simster7** [comment]
> We had feedback from our users that they're surprised that onExit handlers do not run when Workflow is terminated. onExit handlers usually has cleanup routines (cluster deletion, etc).

FYI: Argo 2.6+ now has a `Stop` command that terminates the Workflow and runs all `onExit` handlers.

**Pull request merged**
