### PR TITLE
K8sAPI Executor

### PR DESCRIPTION
**Pull request by dtaniwaki**
I implemented Kubernetes API executor which has been discussed in #902.

Although I implemented the same functions as Kubelet executor, the kubelet originally doesn't work as I submmited the issue #1003. So far, I confirmed `argo logs` and the hello-world, archive-location, scripts-bash and timeouts-step examples work with my Kubernetes API executor, and I tested other functions by returning nil immediately in `Wait()` function of the executor and put a short sleep in workflow steps to workaround the issue #1003.

I think it's enough to use Argo with simple examples like hello-world. Could you consider merging it?

By the way, I use Argo in my company [Preferred Networks](https://www.preferred-networks.jp/en). Please also consider adding my company to the list as described [here](https://github.com/argoproj/argo#who-uses-argo) if it gets merged.

### CODE REVIEW

**Comment by jessesuen** [comment]
@dtaniwaki thanks for submitting this. Given the limitations of the kubelet executor with artifacts, I think this makes sense to go through API server. Will take a look.

**Comment by booninite** [comment]
any progress on this?

**Comment by dtaniwaki** [comment]
I resolved the conflicts w/ the master.

**Comment by andreimc** [comment]
is there any chance to document the 3 executors -> kubelet, docker, k8sapi ?

**Comment by dtaniwaki** [comment]
Any suggestion to get this PR merged? As we already have the kubelet executor which doesn't work with artifacts, having the k8s API executor makes sense although it doesn't work with artifacts perfectly but still better than the kubelet executor. One improvement for these imperfect executors is throwing unsupported feature exceptions on unsupported features respectively.

**Pull request merged**
