### PR TITLE
fix(docker): remove NopCloser from the executor. See #2261

### PR DESCRIPTION
**Pull request by tcolgate**
This ensure that we properly close both stdout and stderr pipes after
executing docker logs.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by tcolgate** [comment]
This is an attempt to resolve #2261.
I'm not sure this is actually the cause, but this seems more correct regardless.

**Comment by alexec** [comment]
I've re-triggered this CI workflow, as it maybe flakey.

**Comment by alexec** [comment]
This should probably be backported  to v2.6.0.

**Comment by alexec** [comment]
Cherry-picked to `release-2.6' for v2.6.1.

**Pull request merged**
