### PR TITLE
fix(ui): Render children of workflow-level onExit. Fixes #3754

### LINKED ISSUE #3754: Exit handler nodes missing from the UI DAG
## Summary 

When a workflow has an exit handler, this should be visible in the UI (as a floating node) but is not visible on latest.  The nodes did actually run.

## Diagnostics

Latest

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes: #3754

From `examples/exit-handlers.yaml`

image

### CODE REVIEW

**Comment by alexec** [comment]
nice

can I ask what testing you performed please?

**Comment by simster7** [comment]
> can I ask what testing you performed please?

I rendered workflows that:
* had no onExit handlers
* had an onExit handler with no child nodes
* had an onExit handler with child nodes that did not collapse
* had an onExit handler with child nodes that collapsed

And verified that all were rendered successfully

**Review by alexec — APPROVED** [review]
We should probably come up with a manual testing script for the UI at some point. I think v2.12 for this one.

**Comment by simster7** [comment]
Back-ported to 2.11

**Pull request merged**
