### PR TITLE
feat: Allow retry strategy on non-leaf nodes, eg for step groups. Fixes #1891

### LINKED ISSUE #1891: Enable retryStrategy to be specified for non-leaf nodes
# Summary

Enable retryStrategy to be specified for non-leaf nodes, so for example it can be applied to a set of steps and they will all be retried if any fail.

# Motivation

For example if there are a pair of steps when one fetches some data and another processes the data, if the processing fails then this is useful if we want to retry the fetch too.

# Proposal

https://github.com/argoproj/argo/pull/1892

### PR DESCRIPTION
**Pull request by mark9white**
Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`. Why? for the release notes. 
* [X] Optional. I've added My organization is added to the README.
* [X] I've signed the CLA and required builds are green. 

Fixes #1891

### CODE REVIEW

**Comment by mark9white** [comment]
Sure - are there any specific scenarios you're thinking of other than the one I already created?

**Comment by alexec** [comment]
@jessesuen do you want to review this one? Or at least provide commentary on the impact on removing this constraint?

**Comment by alexec** [comment]
@mark9white I've tried to fix the conflict - but I think I've failed to do a good job - if you still want this - do you want to take a look?

**Comment by mark9white** [comment]
@alexec I've fixed the conflict

**Pull request merged**
