### PR TITLE
Set executor log level

### PR DESCRIPTION
**Pull request by dtaniwaki**
We use logrus in the executor, but there's no way to control the log level. I think we can have a config for it.

### CODE REVIEW

**Comment by jessesuen** [comment]
@dtaniwaki actually with PR https://github.com/argoproj/argo/pull/1214, this will be supported. I added flag in executor and the ability to set additional args and environment variables in the workflow-controller-configmap

**Comment by dtaniwaki** [comment]
@jessesuen Thank you for implementing it. It’s totally fine if I can configure the log level.

**Comment by jessesuen** [comment]
With PNS merged, I think we can close this. This is how we can add log level arguments to executor:
```
https://github.com/argoproj/argo/blob/master/docs/workflow-controller-configmap.yaml#L100
```

**Comment by dtaniwaki** [comment]
Thanks!

**Pull request closed without merging**
