### PR TITLE
feat(cli): Support `--continue` and `--limit` for `argo list`. Closes #2820

### LINKED ISSUE #2820: Augment `argo list --chunk-size` with `--continue` and `--limit`
# Summary

There is no way to get the next chunk.

# Motivation

* So that we can get the next chunk.
* So we know that there is another chunk.
* Use server side list options.
* Do not default to 500, should be all by default - I think this was a breaking change. 
* Not consistent with `kubectl get`

# Proposal

Edit `cmd/argo/commands/list.go` keep the option like `kubectl get`:

```
kubectl get --help
...
      --chunk-size=500: Return large lists in chunks rather than all at once. Pass 0 to disable. This flag is beta and
may change in the future.
```

We should also support two new options that we can pass directly to `metav1.ListOptions`:

```
--continue string
--limit limit
```

See https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L80

```
if(results == limit) print(“There are additional suppressed results, show them by increasing --continue string”)
```

See #2420 and #2485
---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by changhc**
This PR adds two new arguments to `list`, `--continue` and `--limit`.

I decided to compose a new format of continue tokens instead of using the one returned by the `list` API directly. This is because we apply `since` and `prefix` after calling the API. Take the following case for example,
* A user called `list` with `prefix=A` and `limit=N`
* Due to filtering, we called the list API 6 times to get N workflows. The continue token of page 6 is returned
* Then A called `list` again with `prefix=B` and `limit=N`

If we call the list API starting from page 7, we might miss out workflows prefixed with `B` in pages 1 to 6, which is incorrect. Therefore, I decided to compose a new format of tokens that integrates `prefix` and `since`. If `prefix` or `since` recorded in the token doesn't match the latest value of these argument, this execution will be rejected.

In fact, I could _modify_ the tokens returned by kubernetes API according to [this doc](https://github.com/kubernetes/kubernetes/blob/3e6161883f03597eac4ded7d4ae59c750ad0e1f1/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L456), which makes things easier, but I think it's better that we don't touch it.

Closes #2820. 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to USERS.md.

### CODE REVIEW

**Comment by changhc** [comment]
Is there any easy way to mock workflows? I need mocked workflows for tests.

**Comment by changhc** [comment]
Yes I've seen that PR. Just tried to cover things mentioned in the issue.

**Comment by alexec** [comment]
I'm not sure we need this now, I'm afraid that I think I was wrong about needing these options.

I really appreciate you putting the work into this and raising this PR, and I'm very sorry for asking you to do it. To make this up, next time your raise an issue I'll be sure to expedite it.

**Comment by changhc** [comment]
It's okay. I'll pick up something else. Thanks!

**Pull request closed without merging**
