### PR TITLE
fix(ui): Update workflow drawer with new duration format

### PR DESCRIPTION
**Pull request by rbreeze**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by rbreeze** [comment]
@alexec of course! 
Screen Shot 2020-06-18 at 4 06 41 PM
Screen Shot 2020-06-18 at 4 07 09 PM
Screen Shot 2020-06-18 at 4 07 51 PM
Screen Shot 2020-06-18 at 4 08 29 PM

**Comment by alexec** [comment]
good work - can I ask you to make the workflow details version consistent with this new style?

**Comment by rbreeze** [comment]
definitely - should we potentially have more significant figures in the details view, since presumably the user might want more info there? or is 1 sigfig enough in all use cases?

**Comment by rbreeze** [comment]
Also, by new format do you mean purely the sigfig change, or do you also mean changing the workflow details view to have to rows rather than inline?

**Comment by alexec** [comment]
@rbreeze I just mean when the resource durations are formatted. I think this would just be the case of editing just line 14 of `resources-duration.tsx` to use the same formatting

**Comment by rbreeze** [comment]
@alexec perfect, changed

**Pull request merged**
