### PR TITLE
Fix #1340 parameter substitution bug

### LINKED ISSUE #1340: 2.3.0-rc2 withParams and withItems inflation is shifted
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug report

**What happened**:
repeated steps/tasks using `withParams` and `withItems` have values inflated from the previous index of the loop after the first iteration. 

**What you expected to happen**:
values inflated are from the current index

**How to reproduce it (as minimally and precisely as possible)**:
for withParams: https://github.com/argoproj/argo/blob/master/examples/loops-param-result.yaml

for withItems: https://github.com/argoproj/argo/blob/master/examples/loops.yaml

**Anything else we need to know?**:
previously to the release of 2.3.0-rc2 I was using docker images I built directly off master when head was https://github.com/argoproj/argo/commit/6607dca93db6255a2abc30ae76b5f935fce5735d. Looking at the commits since then I think the issue arose in https://github.com/argoproj/argo/commit/64370a2d185db66a8d2188d986c52a3b73aaf92b#diff-799231f95f7b5d8d9fe078b2cc4ebc1dR186

**Environment**:
- Argo version: 2.3.0-rc2
- Kubernetes version : 1.13.5

**Other debugging information (if applicable)**:
- workflow result:

*withParams*
```
Name:                loops-param-result-bk67x
Namespace:           workflows
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Apr 24 17:02:29 -0400 (48 seconds ago)
Started:             Wed Apr 24 17:02:29 -0400 (48 seconds ago)
Finished:            Wed Apr 24 17:03:17 -0400 (now)
Duration:            48 seconds

STEP                         PODNAME                              DURATION  MESSAGE
 ✔ loops-param-result-bk67x                                                 
 ├---✔ generate              loops-param-result-bk67x-1343984828  9s        
 └-·-✔ sleep(0:20)           loops-param-result-bk67x-826827500   24s       
   ├-✔ sleep(10:30)          loops-param-result-bk67x-2762696320  33s       
   ├-✔ sleep(1:21)           loops-param-result-bk67x-1086122870  26s       
   ├-✔ sleep(2:22)           loops-param-result-bk67x-858747572   25s       
   ├-✔ sleep(3:23)           loops-param-result-bk67x-199114722   26s       
   ├-✔ sleep(4:24)           loops-param-result-bk67x-238287044   28s       
   ├-✔ sleep(5:25)           loops-param-result-bk67x-3020122742  28s       
   ├-✔ sleep(6:26)           loops-param-result-bk67x-4192398476  30s       
   ├-✔ sleep(7:27)           loops-param-result-bk67x-3143246346  32s       
   ├-✔ sleep(8:28)           loops-param-result-bk67x-1592555596  30s       
   └-✔ sleep(9:29)           loops-param-result-bk67x-1728834166  34s 
```

logs for `sleep(2:22)`:
```
$ argo logs -n workflows loops-param-result-bk67x-858747572
sleeping for 21 seconds
done
```
*withItems*
```
Name:                loops-g66xb
Namespace:           workflows
ServiceAccount:      default
Status:              Succeeded
Created:             Wed Apr 24 17:11:25 -0400 (17 seconds ago)
Started:             Wed Apr 24 17:11:26 -0400 (16 seconds ago)
Finished:            Wed Apr 24 17:11:42 -0400 (now)
Duration:            16 seconds

STEP                                   PODNAME                 DURATION  MESSAGE
 ✔ loops-g66xb                                                           
 └-·-✔ print-message(0:hello world)    loops-g66xb-1462947920  13s       
   └-✔ print-message(1:goodbye world)  loops-g66xb-3931292484  13s
```
logs for print-message(1:goodbye world):
```
 _____________ 
< hello world >
 ------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

### PR DESCRIPTION
**Pull request by elikatsis**
Due to wrong `map` initialization, input parameters where appended to `woc.globalParams`.

This PR fixes #1340.

### CODE REVIEW

**Comment by discordianfish** [comment]
Can you add a test for this case to prevent regression?

**Comment by elikatsis** [comment]
Hello @discordianfish.
I tried to add tests but I think the problem is only detectable by checking the results/logs of the tasks run.

What happened exactly is the following:
When `woc.createWorkflowPod()` was called, the template's input parameters were appended to `woc.globalParams`.
Global parameters are first substituted in the template, during `substituteParams()` (called by `common.ProcessArgs()`, which is called by `woc.executeTemplate()`).
So, if a template was reused, these input parameters could find a match.

All in all the following procedure took place:
1. The first template produces the correct results.
2. The second template has its parameters substituted with the first step's parameters (they are saved in `woc.globalParams`, so they are first substituted in `common.ProcessArgs()`).
3. Just before the pod is created, the input parameters are overwritten by the template's input parameters.
4. Then, each template has its parameters substituted with the previous step's parameters.

A test that would cover this case is to check if executing one of the loop workflows (after `woc.createWorkflowPod()` or `woc.executeTemplate()`) `woc.globalParams` remain the same. But I think this would be too specific.
WDYT?

I modified the code a little bit so the `map` is created in the `substitutePodParams()` function, similarly to as it was before #1238.

**Comment by elikatsis** [comment]
@jessesuen @alexmt @edlee2121 
Please take a moment to review and say your opinion on the tests detecting such bug.
Thanks! :slightly_smiling_face:

**Comment by discordianfish** [comment]
Ok, I guess we should get this fix out asap and can address regression testing in another PR.
@jessesuen Can we get this merged soon and release a rc?
This fixes the problem I saw too.

**Pull request merged**
