### PR TITLE
Handle sidecar killing properly

### PR DESCRIPTION
**Pull request by dtaniwaki**
Fixes: #1674 

I changed the logic of killing sidecars so we can still stop on a failure of the post process.

### CODE REVIEW

**Comment by dtaniwaki** [comment]
@ddseapy @jessesuen 
I'm not sure if this change breaks what #1645 wanted to fix. Could you review it?

**Comment by dtaniwaki** [comment]
Or, we could just check added errors before returning from the post process and make the container fail.

**Comment by ddseapy** [comment]
Looks good to me.  I can test it out today to make sure it still works with istio.

**Comment by ddseapy** [comment]
Just ran this branch with Istio sidecar injected and works as expected.

**Pull request merged**
