### PR TITLE
go.mod: use version suffix appropriate for tag

### LINKED ISSUE #2602: import latest v2.7.0 argo version in go project
# Summary

How can I import latest argo in go project?

# Motivation

Why do you need to know this, any examples or use cases you could include?
when I want import argo v2.7.0 in my project
```
go get github.com/argoproj/argo@v2.7.0
```
But I got error
```
not found: github.com/argoproj/argo@v2.7.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
How to fix it?

### PR DESCRIPTION
**Pull request by peterbourgon**
Follow-on from #4183 

If your repo has a tag that Go modules parses as semver (like v2.11.1) then the module name in the corresponding go.mod must meet Go modules' expectations, specifically if it is v2 or above it must include a /vN version suffix. If you don't do this, your project is essentially unusable by consumers.

After discussion in #4183 I've bumped the version to v3 and made the necessary changes to import paths. If and when this merges to main, you'll need to tag v3.0.0 for it to all work properly.

Fixes #2602

### CODE REVIEW

**Comment by alexec** [comment]
@peterbourgon we may be making some big changes soon and we may well want to fix this problem. Can we close this for the moment, and then I'd like to get you involved in that work?

**Comment by peterbourgon** [comment]
Happy to advise.

**Comment by alexec** [comment]
@peterbourgon I think we're essentially green-lighted for v3. Do you want to complete this PR to help drive this forward? I can see several build jobs need fixing.

**Comment by peterbourgon** [comment]
I don't have enough domain knowledge of the project to make meaningful progress on those. I'm happy to advise whoever can drive the work about modules-related errata.

**Pull request closed without merging**
