### PR TITLE
chore(ui): Remove unused SidecarOptions model interface

### PR DESCRIPTION
**Pull request by terrytangyuan**
Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by simster7** [comment]
If we’re going to take the decision to remove these unused interfaces, can we do it all in one PR as opposed to many smaller ones?

Although I am not sure why removing them is even necessary or desirable.

**Comment by terrytangyuan** [comment]
This is the last one I found while going through the codebase. Is there any good tool we can leverage to find them all? I am in favor of removing them for now and adding only when needed/used to reduce code complexity and maintenance efforts. This type of code gets updated very easily. Just my two cents though.

**Comment by simster7** [comment]
I think we’re in the process of auto generating TypeScript types out of our Swagger definitions anyway. Can we wait to see how that resolves before attempting to remove unused types?

**Comment by terrytangyuan** [comment]
Sure, that's even better. Closing this now.

**Pull request closed without merging**
