### PR TITLE
Issue #660 - Support rendering logs from all steps using 'argo logs' command

### PR DESCRIPTION
**Pull request by alexmt**
Implements Issue #660

### CODE REVIEW

**Comment by jessesuen** [comment]
I built your branch to try out the feature but I wasn't able to get it to work. It mostly just hangs with no output. I tried the `examples/loops-maps.yaml` example. I also tried running it against non-existant workflow/pod and it hangs as well.

It seems to behave like before, if i run it against a single pod.

**Comment by alexmt** [comment]
Thank for testing it. @jessesuen . This fixes hanging issue: https://github.com/argoproj/argo/pull/792/commits/5ef9c10b0467f6035bd2d3895f356569c28d32b0 

I've realized there is another issue. If 'follow' flag is set, then 'logs' command is supposed to wait until workflow is completed and should stream logs of new steps. Working on it now.

**Comment by jessesuen** [comment]
It looks like theres still an issue in which that argo logs <nonexistantpod> does not indicate that the pod or workflow doesn't exist. 

Compare old behavior:
```
$ /usr/local/bin/argo logs ci-example-fjn6d-2799764913
Error from server (NotFound): pods "ci-example-fjn6d-2799764913" not found
FATA[0000] exit status 1
```
vs. the new behavior which simply returns you to the shell
```
$ argo logs ci-example-fjn6d-2799764913
$ echo $?
0
```
Also kubectl:
```
$ kubectl logs ci-example-fjn6d-2799764913
Error from server (NotFound): pods "ci-example-fjn6d-2799764913" not found
```

Also, I'm still not able to get it to show the merged logs. See the following:
```
$ argo version
argo: v2.1.0+5ef9c10
  BuildDate: 2018-03-12T09:16:55Z
  GitCommit: 5ef9c10b0467f6035bd2d3895f356569c28d32b0
  GitTreeState: clean
  GoVersion: go1.10
  Compiler: gc
  Platform: darwin/amd64

$ argo get ci-example-k2kz4
Name:                ci-example-k2kz4
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Created:             Mon Mar 12 02:22:04 -0700 (3 minutes ago)
Started:             Mon Mar 12 02:22:06 -0700 (3 minutes ago)
Finished:            Mon Mar 12 02:25:37 -0700 (8 seconds ago)
Duration:            3 minutes 31 seconds
Parameters:
  revision:          master

STEP                                   PODNAME                      DURATION  MESSAGE
 ✔ ci-example-k2kz4
 ├---✔ build                           ci-example-k2kz4-3736352317  2m
 └-·-✔ test(0:image:debian,tag:9.1)    ci-example-k2kz4-1377853457  27s
   ├-✔ test(1:image:alpine,tag:3.6)    ci-example-k2kz4-3490015573  17s
   └-✔ test(2:image:ubuntu,tag:17.10)  ci-example-k2kz4-1861524042  27s

$ argo logs ci-example-k2kz4 # this has no output
$ argo logs ci-example-k2kz4-3736352317 # but this does
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
github.com/golang/example/stringutil
github.com/golang/example/hello
```

**Comment by alexmt** [comment]
The missing error message is added back and `logs` command now stream logs of new workflow pods while it is running.  

@jessesuen  Command `argo logs ci-example-k2kz4` did not give output since 'ci-example-k2kz4' was considered as pod name, not workflow name. I've added flag '-w' to indicate that merged workflow logs should be streamed. PTAL

**Comment by alexmt** [comment]
@sandeepbhojwani , @jessesuen please take a look when you have time.

**Comment by alexmt** [comment]
@sandeepbhojwani , Thanks for review!

**Pull request merged**
