### PR TITLE
feat: Attempt to resolve nested tags

### PR DESCRIPTION
**Pull request by simster7**
Closes: https://github.com/argoproj/argo/issues/3319

### CODE REVIEW

**Comment by alexec** [comment]
Could we use the new expr library for this?

**Comment by simster7** [comment]
> Could we use the new expr library for this?

No, this is unrelated to expression evaluation

**Comment by alexec** [comment]
my thought is that perhaps using expr might be better as it would be better compatible with Helm, it would not have `{{` or `}}`:

```
    steps:
    - - name: parallel-worker
        template: seq-worker
        arguments:
          parameters:
          - name: seq-list
            valueFrom
              expression: inputs.parameters["seq-list"]
```

**Comment by simster7** [comment]
That would be a significant overhaul of the Argo Variable system that could produce many breaking changes and bugs.

For example, a big reason why we use the `{{` and `}}` syntax is because as part of our variable resolution process, we marshal entire (deep) Go structs (such as wfv1.Template) into JSON, perform the substitution as strings, then Unmarshal back into Go struct. Because it is impossible to have two open curly brackets (`{{`) in valid JSON, this serves as a guarantee that whenever we encounter them in the string it is an Argo variable that needs resolution.

If we were to use expr for variable resolution, we couldn't make use of this strategy (which I think is fairly efficient), and could introduce bugs and breaking changes for virtually no benefit.

**Comment by simster7** [comment]
Another key point is that Argo variables may be found anywhere in the template definition, not necessarily in dedicated fields such as `valueFrom.expression`.

**Comment by simster7** [comment]
Regardless, that change would be out of scope for this PR

**Comment by alexec** [comment]
I tried and failed to get something useful working with expr because our templating is deeply entrenched in the code base and is just more flexible.

What about allowing different start (`{{`) and end tags (`}}`) based on annotation or similar?

**Comment by simster7** [comment]
> What about allowing different start ({{) and end tags (}}) based on annotation or similar?

See https://github.com/argoproj/argo/issues/2430#issuecomment-632862338

**Comment by simster7** [comment]
@alexec Please review when convenient

**Pull request merged**
