### PR TITLE
fix: Say no logs were outputted when pod is done

### LINKED ISSUE #2372: If a step outputs no logs, the Logs display in the UI will show "Waiting for data..." forever
**What happened**:
Have a step with no output. Click "Logs" in UI. Says "Waiting for data..." forever instead of telling you the logs are blank.

**What you expected to happen**:
Message saying "This container did not output any logs" or similar.

**Environment**:
- Argo version:
Using `argoproj/argoexec:latest`

```
$ argo version
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:01Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-11-13T11:23:11Z"
  compiler: gc
  gitCommit: b3cbbae08ec52a7fc73d334838e18d17e8512749
  gitTreeState: clean
  gitVersion: v1.16.3
  goVersion: go1.12.12
  major: "1"
  minor: "16"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-01-18T23:22:30Z"
  compiler: gc
  gitCommit: 59603c6e503c87169aea6106f57b9f242f64df89
  gitTreeState: clean
  gitVersion: v1.17.2
  goVersion: go1.13.5
  major: "1"
  minor: "17"
  platform: linux/amd64
```

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2372. Thanks @foobarbecue!

### CODE REVIEW

**Comment by foobarbecue** [comment]
This might have caused another issue. I now sometimes get "Pod did not output any logs." but then when I go to Artifacts for the same Pod, there are logs there. I think this might have to do with log rotation settings.

**Comment by foobarbecue** [comment]
Actually I think what was happening was that I'm using retryStrategy and the logs only show up on the child nodes representing retries, and not on the parent. Note that I'm using a version without the #2384 fix so all of my nodes have a (0) version even if they worked the first time. These are the ones where "logs" shows output on the (0) node but not on its parent. Both the parent and (0) node have archived logs accessible.

**Comment by simster7** [comment]
> Actually I think what was happening was that I'm using retryStrategy and the logs only show up on the child nodes representing retries, and not on the parent. Note that I'm using a version without the #2384 fix so all of my nodes have a (0) version even if they worked the first time. These are the ones where "logs" shows output on the (0) node but not on its parent. Both the parent and (0) node have archived logs accessible.

Hi @foobarbecue, this is actually the correct behavior. The parent node is something we call a "virtual node" of type `RetryNode` which basically means that the node itself will not run a pod, but will point to other nodes that will – so the `RetryNode` should never contain logs. #2384 should help in addressing this, but the full solution to this problem should be #2406 if you're interested in contributing 😄

**Comment by foobarbecue** [comment]
Hi @simster7 , I see. I haven't been able to get my build environment set up yet, but I'll probably work on it some more this evening and if I can get it going I'll see if I think #2406 is within my abilities!

**Comment by simster7** [comment]
Back-ported to 2.6

**Pull request merged**
