### PR TITLE
feat(ui): Visualisation of the suspended CronWorkflows in the list. Fixes #4264

### LINKED ISSUE #4264: Visualisation of the suspended CronWorkflows in the list
# Summary

When displaying the CronWorkflows, it would be great to have a quick overview of the suspended (or not) workflows. Therefore, the clock icon could be changed into a paused icon for the suspended CronWorkflows.

# Use Cases

When willing to see if a certain CronWorkflow is scheduled or not.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by Nicwalle**
Fixes #4264 

Shows the suspended CronWrokflows inside the list. 
Pause icon if suspended, clock icon if not (same icon as previously)

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by Nicwalle** [comment]
Does anyone mind helping me ? I don't understand what I did wrong. This is my first PR on such a big project. I just made a small UI change and the test "Ensure nothing changed" fails of course. By the way, I don't understand the DCO error either.

Thanks in advance

**Review by simster7 — APPROVED** [review]
LGTM!

**Comment by simster7** [comment]
@Nicwalle you need to run `yarn lint` inside the `argo/ui/` directory.

**Comment by Nicwalle** [comment]
> @Nicwalle you need to run `yarn lint` inside the `argo/ui/` directory.

Thanks a lot, it worked

**Pull request merged**
