### PR TITLE
feat(crds): Update CRDs to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by naor2013** [comment]
Is there a way to keep the old version still as well? Either with a helm chart that detects your k8s version automatically or simply by keeping both version and labeling the old version with "old" (for example, "namespace_install_old.yaml")?

**Comment by alexec** [comment]
> Is there a way to keep the old version still as well? Either with a helm chart that detects your k8s version automatically or simply by keeping both version and labeling the old version with "old" (for example, "namespace_install_old.yaml")?

What about producing two sets of CRDs?

**Comment by naor2013** [comment]
> What about producing two sets of CRDs?

That would also help, if there would be 2 versions of CRD and we could choose the "old one".

**Comment by alexec** [comment]
https://kubernetes.io/blog/2019/06/20/crd-structural-schema/

**Comment by alexec** [comment]
Re-running TestSubmitWorkflowTemplate

**Comment by alexec** [comment]
This time TestDeletingRunningPod failed.

**Review by simster7 — APPROVED** [review]

**Comment by naor2013** [comment]
@alexec what about what we wrote here before? Having two sets of CRDs to keep the old version as well?

**Comment by alexec** [comment]
Could you use the old CRDs on the release-2.12 branch?

**Comment by naor2013** [comment]
> Could you use the old CRDs on the release-2.12 branch?

Now it seems like there isn’t much difference between 2.12 and 3.0 so it’s possible, but the moment you’ll change the yamls in version 3.x, it won’t be possible anymore.

**Pull request merged**
