### PR TITLE
fix: MySQL config fix

### PR DESCRIPTION
**Pull request by fabio-rigato**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to USERS.md.

### CODE REVIEW

**Comment by sh-tatsuno** [comment]
I have just encountered a problem which may be solved by this PR.
It would be appreciated if the PR is incorporated into master ASAP.

**Comment by alexec** [comment]
Can you please sync with master

**Comment by fabio-rigato** [comment]
@alexec how can I do it?

**Comment by alexec** [comment]
Merged!

**Comment by fabio-rigato** [comment]
My first PR yeah! =)

**Pull request merged**
