### PR TITLE
feat(server): Support email for SSO+RBAC. Closes #4612

### LINKED ISSUE #4612: Use Email for SSO RBAC with Google OIDC
# Summary

When using SSO auth mode with Google's OIDC, the issuer identifier (subject) is a unique user ID that isn't very useful and is hard to use for identifying users and managing RBAC permissions in a scalable way.

It will be more useful to use the user's email as the subject when using google as the OIDC provider.
per Google's [OIDC documentation](https://developers.google.com/identity/protocols/oauth2/openid-connect):

```json
{
  "iss": "https://accounts.google.com",
  "azp": "1234987819200.apps.googleusercontent.com",
  "aud": "1234987819200.apps.googleusercontent.com",
  "sub": "10769150350006150715113082367",
  "at_hash": "HK6E_P6Dh8Y93mRNtsDB1Q",
  "hd": "example.com",
  "email": "jsmith@example.com",
  "email_verified": "true",
  "iat": 1353601026,
  "exp": 1353604926,
  "nonce": "0394852-3190485-2490358"
}
```

# Use Cases

When google is set as the OIDC provider (issuer `https://accounts.google.com`). This is very useful for teams using G suite.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Closes #4612

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Screenshot 2020-12-03 at 12 46 08

### CODE REVIEW

**Comment by alexec** [comment]
Testing by end user was successful.

**Comment by alexec** [comment]
@jessesuen can you please approve the very small + low risk proto changes?

**Review by jessesuen — APPROVED** [review]

**Comment by alexec** [comment]
@simster7 @sarabala1979 this has been proto-approved by @jessesuen. Should be easy to review.

**Comment by alexec** [comment]
@simster7 @sarabala1979 bump!

**Comment by simster7** [comment]
This is out on https://github.com/argoproj/argo/releases/tag/v2.12.6

**Pull request merged**
