### PR TITLE
Build docker image for ppc64le platform

### PR DESCRIPTION
**Pull request by wzhanw**
Docker image for ppc64le platform.
Created a new Dockerfile named "Dockerfile.ppc64le"
Update Makefile to invoke different Dockerfile automatically according to the machine's arch

### CODE REVIEW

**Comment by Ark-kun** [comment]
> Created a new Dockerfile named "Dockerfile.ppc64le"

I'm not sure I see that file in the change list.

What are the changes there compared to the existing Dockerfile?

**Comment by wzhanw** [comment]
> > Created a new Dockerfile named "Dockerfile.ppc64le"
> 
> I'm not sure I see that file in the change list.
> 
> What are the changes there compared to the existing Dockerfile?

@Ark-kun sorry, I forgot to add the file, I added the Dockerfile.ppc64le file, please review again.
There is only a little difference with the original one. See the diff below:
```
--- Dockerfile	2019-10-09 06:11:05.000000000 -0700
+++ Dockerfile.ppc64le	2019-10-09 06:46:50.305939307 -0700
@@ -18,25 +18,26 @@

 # Install docker
 ENV DOCKER_CHANNEL stable
-ENV DOCKER_VERSION 18.09.1
-RUN wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" && \
+ENV DOCKER_VERSION 18.06.3-ce
+ENV ARCH ppc64le
+RUN wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${ARCH}/docker-${DOCKER_VERSION}.tgz" && \
     tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/ && \
     rm docker.tgz

 # Install dep
 ENV DEP_VERSION=0.5.0
-RUN wget https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -O /usr/local/bin/dep && \
+RUN wget https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-${ARCH} -O /usr/local/bin/dep && \
     chmod +x /usr/local/bin/dep

 # Install golangci-lint
-ENV GOLANGCI_LINT_VERSION=1.16.0
-RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v$GOLANGCI_LINT_VERSION/install.sh| sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VERSION
+#ENV GOLANGCI_LINT_VERSION=1.16.0
+#RUN curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/v$GOLANGCI_LINT_VERSION/install.sh| sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VERSION

 # Install gometalinter
 # Keep gometalinter to avoid CI failures during the linter migration.
 # We can remove it after enough time has passed.
-ENV GOMETALINTER_VERSION=2.0.12
-RUN curl -sLo- https://github.com/alecthomas/gometalinter/releases/download/v${GOMETALINTER_VERSION}/gometalinter-${GOMETALINTER_VERSION}-linux-amd64.tar.gz | \
+ENV GOMETALINTER_VERSION=3.0.0
+RUN curl -sLo- https://github.com/alecthomas/gometalinter/releases/download/v${GOMETALINTER_VERSION}/gometalinter-${GOMETALINTER_VERSION}-linux-${ARCH}.tar.gz | \
     tar -xzC "$GOPATH/bin" --exclude COPYING --exclude README.md --strip-components 1 -f- && \
     ln -s $GOPATH/bin/gometalinter $GOPATH/bin/gometalinter.v2

@@ -51,7 +52,7 @@
 RUN apt-get update && \
     apt-get install -y curl jq procps git tar mime-support && \
     rm -rf /var/lib/apt/lists/* && \
-    curl -L -o /usr/local/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl && \
+    curl -L -o /usr/local/bin/kubectl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/${ARCH}/kubectl && \
     chmod +x /usr/local/bin/kubectl
 COPY hack/ssh_known_hosts /etc/ssh/ssh_known_hosts
 COPY --from=builder /usr/local/bin/docker /usr/local/bin/
@@ -75,7 +76,7 @@
 # Perform the build
 WORKDIR /go/src/github.com/argoproj/argo
 COPY . .
-ARG MAKE_TARGET="controller executor cli-linux-amd64"
+ARG MAKE_TARGET="controller executor cli-linux-${ARCH}"
 RUN make $MAKE_TARGET


@@ -98,5 +99,5 @@
 # argocli
 ####################################################################################################
 FROM scratch as argocli
-COPY --from=argo-build /go/src/github.com/argoproj/argo/dist/argo-linux-amd64 /bin/argo
+COPY --from=argo-build /go/src/github.com/argoproj/argo/dist/argo-linux-ppc64le /bin/argo
 ENTRYPOINT [ "argo" ]
```

**Comment by Ark-kun** [comment]
What do you think about adding the `ARCH` argument to the existing Dockerfile.
When files are forked they can diverge pretty quickly.

**Comment by wzhanw** [comment]
> What do you think about adding the `ARCH` argument to the existing Dockerfile.
> When files are forked they can diverge pretty quickly.

aha, I really agree with you,  I had thought that at the beginning,  but I found the `golangci-lint` doesn't have power arch support,  and DOCKER_VERSION 18.09.1 doesn't have power support.
I have to comment the `golangci-lint` in builder-image and change the version of Docker.

**Comment by wzhanw** [comment]
other thoughts, I'm afraid you guys don't like me to touch the original Dockerfile.

**Comment by alexec** [comment]
@wzhanw do you still want this please?

**Comment by alexec** [comment]
This was completed in another PR.

**Pull request closed without merging**
