### PR TITLE
fix(Makefile): removed deprecated k3d cmds. Fixes #4206

### LINKED ISSUE #4206: Makefile seems to have deprecated k3d commands
## Summary 

What happened/what you expected to happen?

After starting k3d cluster locally, if I run `make start` I get an error
```
➜  argo git:(learning) ✗ make start
# GIT_TAG=v2.10.0-rc1, GIT_BRANCH=learning, GIT_TREE_STATE=dirty, VERSION=latest, DEV_IMAGE=true, K3D=true
killall argo workflow-controller kubectl || true
No matching processes belonging to you were found
k3d start
Error: unknown command "start" for "k3d"
Run 'k3d --help' for usage.
FATA[0000] unknown command "start" for "k3d"            
make: *** [install] Error 1
➜  argo git:(learning) ✗ kubectl cluster-info
Kubernetes master is running at https://0.0.0.0:61662
CoreDNS is running at https://0.0.0.0:61662/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://0.0.0.0:61662/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

## Diagnostics

What Kubernetes provider are you using? 
`K3d`
What version of Argo Workflows are you running? 
```
argo: latest+9319c07.dirty
  BuildDate: 2020-10-03T06:45:57Z
  GitCommit: 9319c074e742c5d9cb97d6c5bbbf076afe886f76
  GitTreeState: dirty
  GitTag: v2.10.0-rc1
  GoVersion: go1.14.3
  Compiler: gc
  Platform: darwin/amd64
```
This line here for ref: https://github.com/argoproj/argo/blob/300634af42a3017a5354468a2779ef1fa5e37931/Makefile#L326
```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by kpr6**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 

PR related to: https://github.com/argoproj/argo/issues/4206

Removed the `if` clause completely coz `k3d start` doesn't mean anything there and `make start` seems to be alright, brings up both `argo-server` and `workflow-controller`. As for `github/workflow/ci-build.yaml` I don't think it's needed, coz I don't see any `k3d` commands in there, only `make start` ones which should be fine?

Also, changed context check as k3d prefixes `k3d-` to any cluster which user created and updates kubeconfig automatically.

### CODE REVIEW

**Review by alexec — CHANGES_REQUESTED** [review]
You need to update ` .github/workflows/ci-build.yaml` too please.

**Comment by kpr6** [comment]
I'm afraid I can't figure out what to update in there coz `Makefile` targets haven't changed. Any help pls?

**Comment by alexec** [comment]
You'll need to change this block to install the new version:

```yaml
      - name: Install and start K3S v1.0.1
        if: ${{ matrix.test != 'test' }}
        run: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.0.1 INSTALL_K3S_EXEC=--docker K3S_KUBECONFIG_MODE=644 sh - &

```

**Comment by alexec** [comment]
@kpr6 if I merge this, and it breaks, will you be available to help fix today please?

**Comment by kpr6** [comment]
It's around 23:30 here where I stay (IST). But yes, I'll be around tomorrow to take care if something unexpected pops up :)

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
https://github.com/argoproj/argo/actions/runs/296043078

**Pull request merged**
