### PR TITLE
fix(k8sapi-executor): Fix KillContainer impl

### PR DESCRIPTION
**Pull request by twz123**
Problem:
The Kubernetes API rejects exec calls that won't have at least one open
standard stream. When the k8sapi executor invokes the KillContainer
method, it tries to do so with no stream open at all, resulting in an
error: "Failed to kill main container: unable to upgrade connection: you
must specify at least 1 of stdin, stdout, stderr".

Changes:
Request stderr instead of nothing in the KillContainer implementation
of the k8sapi executor.

Result:
The k8sapi executor can successfully send the kill command to pods.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by alexec** [comment]
Can I please ask how you to would want to test this?

**Comment by twz123** [comment]
I tested it manually, after troubleshooting the mentioned error message. I didn't spot any tests at all for the k8sapi executor at all in the current code base, that's why I didn't try to add tests for this from scratch. Unit tests won't make sense for this kind of error, so e2e would be the best option. I can try to add e2e tests, but I'd definitely need assistance.

**Comment by alexec** [comment]
I have `git merge master` into your branch to trigger CI again.

**Comment by twz123** [comment]
@alexec done!

**Pull request merged**
