### PR TITLE
ci: Fix broken Multiplatform builds

### PR DESCRIPTION
**Pull request by dgiebert**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Closes: https://github.com/argoproj/argo/issues/3866

I tried it here:
- https://github.com/dgiebert/argo/runs/1051395687?check_suite_focus=true

Also see here: https://hub.docker.com/repository/docker/dgiebert/argoexec/tags?page=1

P.S: Added JOBS=max to use more cores for node-gyp

### CODE REVIEW

**Comment by alexec** [comment]
@sarabala1979 is `JOBS=max` the same fix you used

**Comment by dgiebert** [comment]
Maybe we should remove the build-linux dependency on the last stage to speed up the builds ?

**Comment by dgiebert** [comment]
@alexec Can you retrigger something during upload failed in the last step :facepalm:

**Comment by alexec** [comment]
Re-ran jobs. Same error.

**Comment by dgiebert** [comment]
Somehow it worked here: https://github.com/argoproj/argo/actions/runs/234936527

**Pull request merged**
