### PR TITLE
Auto-complete workflow names

### PR DESCRIPTION
**Pull request by dtaniwaki**
I added auto-completion for workflows.
https://github.com/spf13/cobra/pull/730
I had to update cobra to [avoid `custom_func` overiding](https://github.com/spf13/cobra/pull/730).

### CODE REVIEW

**Comment by jessesuen** [comment]
The changes to the Gopkg.lock look unexpected for just updating cobra. Which version of dep are you using? We should be on v0.5

**Comment by dtaniwaki** [comment]
Mine is `v0.4.1`. I'll update dep and fix the unnecessary diffs.

**Comment by dtaniwaki** [comment]
@jessesuen I fixed it. By the way, do you think we should rather fix the reversion in `Gopkg.toml`?

**Comment by jessesuen** [comment]
> By the way, do you think we should rather fix the reversion in Gopkg.toml

If there's a semversion with the needed fix, sure. I just don't like locking to specific revision commit SHAs unless absolutely necessary (e.g. the upstream package does not use semvers). I'm fine either way.

**Comment by dtaniwaki** [comment]
I do feel like the same. :) I locked it in Gopkg.toml. We can update it once they make a release.

**Pull request merged**
