### PR TITLE
fix: Simplify the WorkflowTemplateRef field validation to support all fields in WorkflowSpec except `Templates`

### LINKED ISSUE #3355: Unable to use workflowTemplateRef with defaults workflow serviceAccountName
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Ever since the validation changes were introduced in https://github.com/argoproj/argo/pull/2912 we are unable to submit a workflow using a `workflowTemplateRef` when there is an `serviceAccountName` defined in workflow defaults, given the following defaults:

```
workflowDefaults:
  serviceAccountName: argo-workflow
```

When submitting the following workflow:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: foo-fw4vp
  namespace: models
spec:
  arguments:
    parameters:
  serviceAccountName: argo-workflow
  workflowTemplateRef:
    name: foo
```

 it raises the following error:

```ServiceAccountName is invalid field in spec if workflow referred WorkflowTemplate reference```

**What you expected to happen**:

That this will work as it did prior to these changes.

**How to reproduce it (as minimally and precisely as possible)**:

Configure argo with the workflow defaults configmap defining a default `serviceAccountName` and submit a workflow using a `workflowTemplateRef`.

**Environment**:

- Argo version: `2.9.0-RC4`
- Kubernetes version : `1.15`

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  Fixes #3355
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by sarabala1979** [comment]
yes

**Comment by alexec** [comment]
Fixed and available in v2.10.0-rc5.

**Comment by vladlosev** [comment]
Thanks! I see it has also been backported to the 2.9 branch. Can you please tag a point release on that branch with the fix?

**Comment by alexec** [comment]
Available in [v2.9.5](https://github.com/argoproj/argo/releases/tag/v2.9.5)

**Pull request merged**
