### PR TITLE
feat(controller): Only re-queue workflow on generation change

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
@jessesuen @whynowy this passes functional tests on first try.

**Comment by jessesuen** [comment]
I doubt it can be as simple as this, without a lot of unintentional side-effects. For one, we aren't leveraging status sub-resources in the CRD. This means that generation is essentially acting like `metadata.resourceVersion` because it gets incremented on any change to the object.

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#status-subresource

**Comment by alexec** [comment]
I'm closing this pending @whynowy investigate.

**Comment by alexec** [comment]
```
(⎈ |k3d-k3s-default:argo)➜  argo git:(emissary) k patch wf hello-world-848fs -p '{"spec":{"unschedulable":true}}' --type merge
workflow.argoproj.io/hello-world-848fs patched
(⎈ |k3d-k3s-default:argo)➜  argo git:(emissary) k d wf|grep 'Name\|Generation\|Resource Version'                                 
Name:         hello-world-848fs
Namespace:    argo
  Generate Name:       hello-world-
  Generation:          2
        f:generateName:
  Resource Version:  24417
      Name:   
    Name:  whalesay
(⎈ |k3d-k3s-default:argo)➜  argo git:(emissary) k patch wf hello-world-848fs -p '{"status":{"unschedulable":true}}' --type merge 
workflow.argoproj.io/hello-world-848fs patched
(⎈ |k3d-k3s-default:argo)➜  argo git:(emissary) k d wf|grep 'Name\|Generation\|Resource Version'                                
Name:         hello-world-848fs
Namespace:    argo
  Generate Name:       hello-world-
  Generation:          3
        f:generateName:
  Resource Version:  24432
      Name:   
    Name:  whalesay
```

This example shows this does not work.

**Pull request closed without merging**
