### PR TITLE
docs: Update quick-start and running-locally docs to help with running locally Argo

### PR DESCRIPTION
**Pull request by alfsuse**
Adding a way for users to experiment with Argo through a fully automated setup leveraging project k3ai. The goal of the project hence the reason to use it within Argo documentation is to provide community folks an easy way to setup a local environment closest as possible to what they may have in their DataCentre/Cloud envs.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
Thank you for your PR. We don't recommend to our users installing from a source we don't control for security reasons.  Nor do we promote any other tools that use Argo under the hood (e.g. Kubeflow)

However, would this be something you'd be interested in talking about at a future community meeting?

**Comment by alfsuse** [comment]
> Thank you for your PR. We don't recommend to our users installing from a source we don't control for security reasons. Nor do we promote any other tools that use Argo under the hood (e.g. Kubeflow)
>
My bad I looking in retrospect I should have reached out to everyone in the slack channel and ask if that was something people were looking for before open the PR. So sorry about shooting this in the wild and thanks for the explanation! :)

> However, would this be something you'd be interested in talking about at a future community meeting?
>
Absolutely yes! Whenever you feel we (me and @Gsantomaggio) can present to the community meeting we will be in.. also could be a great way to understand if the Argo community is interested in having other solutions (Events,CD) supported in k3ai!

**Pull request closed without merging**
