### PR TITLE
Change 'continue-on-fail' example to better reflect its description

### PR DESCRIPTION
**Pull request by thundergolfer**
Researching how this `parallelism` config feature functions and came across this example that I think wasn't accurately reflecting the description it had at the top of the file. 

PS. Great work on Argo!

### CODE REVIEW

**Comment by xianlubird** [comment]
What's the effect on `parallelism ` add to the example ?

**Comment by thundergolfer** [comment]
See description of the example:

> Example on **specifying parallelism** on the outer workflow and limiting the number of its [emphasis mine]

Given that description it seems wrong to me that the config doesn't actually specify the `parallelism` value.

**Comment by xianlubird** [comment]
OK  LGTM  

ping @sarabala1979

**Comment by sarabala1979** [comment]
I didn;t see any difference in execution. Can you provide more information what this change is doing?

**Comment by thundergolfer** [comment]
@sarabala1979 Perhaps the description of this example is what's incorrect. 

The file is named `continue-on-fail`, and there is a continue-on-fail feature on `C`. The description mentions `parallelism`, but there's nothing I see in the example that is "specifying parallelism on the outer workflow" (<- from description). 

Without knowing for sure what this example is supposed to demonstrate, it's hard to say what aspect of it should be changed, but I do think right now it's a confusing example.

**Pull request merged**
