### PR TITLE
feat(controller): Workflow-level `retryStrategy`/resubmit pending pods by default. Closes #3918

### LINKED ISSUE #3918: Tolerate deleted resources
# Summary

When a pod or node is deleted due to what ever reason, the workflow always error (see #3751). There is strong evidence that this is not what what users want by default.

Work-arounds:

- `rebumitPendingPods: true` a per-template setting (must therefore be set on all templates - no global default). This only works for deletion.
- `retry: {limit:1}` - again - per-template setting. 

Options

- Per-workflow (which can them be configured globally) versions of `resubmitPendingPods`.

# Use Cases

Argo Workflows has a challenge in that it tries to reliably execute workflows on fundamentally unreliably architecture.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Closes #3918
Related to ##2385

# Changes

* Support `retryStrategy` at workflow level.
* Completely remove `resubmitPendingPods` and always resubmit them.

### CODE REVIEW

**Comment by alexec** [comment]
```
FAIL: TestFunctionalSuite/TestRetryStrategy 
```

**Comment by alexec** [comment]
FAIL: TestArgoServerSuite/TestWorkflowService/Terminate 
FAIL: TestArgoServerSuite/TestWorkflowService/Resubmit
FAIL: TestCLIWithServerSuite/TestNodeSuspendResume

**Comment by alexec** [comment]
```
FAIL: TestFunctionalSuite/TestDeletingRunningPodWithOrErrorRetryPolicy (39.99s)
```

**Review by jessesuen — APPROVED** [review]

**Review by jessesuen — APPROVED** [review]

**Comment by jamesgunnfiveai** [comment]
Hi folks - we've just bumped into a problem where some users with clients on 2.12.x can't parse our workflows that contain `resubmitPendingPods: true` whereas 2.11.x clients can. I believe this is a result of this MR removing the field in versions >=2.12 (this is solved by just having them downgrade to 2.11.x for now). Just curious whether it was intentional that this landed in a minor version bump as I would have thought it should be major according to semver.

**Pull request merged**
