### PR TITLE
fix(cli)!: Enable CLI to work without kube config. Closes #3383, #2793

### LINKED ISSUE #3383: CLI unusable without KUBECONFIG
It should be possible to use the CLI without having a valid KUBECONFIG, by setting ARGO_SERVER and ARGO_TOKEN, but this is not the case :(

```
FATA[0000] invalid configuration: no configuration has been provided
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by hadim** [comment]
It says "server only mode". Would that possible/easy for you to add client mode to this? So we could use `argo` with the cluster URL + a token?

**Comment by alexec** [comment]
> It says "server only mode". Would that possible/easy for you to add client mode to this? So we could use `argo` with the cluster URL + a token?

This is intended to allow you to use the Argo CLI without any local Kubernetes configuration, just so long as you have an Argo Server available (i.e. `ARGO_SERVER` is set).

**Comment by alexec** [comment]
@whynowy can I please ask you to review? You've worked in some of this code before and Simon/Bala are probably busy with bug squashing.

**Comment by hadim** [comment]
Even if the server is in client only mode? Great in that case.

**Pull request merged**
