### PR TITLE
fix: the ParallelSteps in the swagger definition

### PR DESCRIPTION
**Pull request by vilmosnagy**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by vilmosnagy** [comment]
The Swagger definition is fixed in this PR, cause the `steps` should be defined this way:

```yaml
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello1"}]
    - - name: hello2a
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2a"}]
      - name: hello2b
        template: whalesay
        arguments:
          parameters: [{name: message, value: "hello2b"}]
```
(see: https://github.com/argoproj/argo/blob/master/examples/steps.yaml)

But the current Swagger definition suggests the following:

```yaml
templates:
  - name: hello-hello-hello
    steps:
      - steps:
          - name: hello1
            template: whalesay
            arguments:
              parameters: [{name: message, value: "hello1"}]
      - steps:
          - name: hello2a
            template: whalesay
            arguments:
              parameters: [{name: message, value: "hello2a"}]
          - name: hello2b
            template: whalesay
            arguments:
              parameters: [{name: message, value: "hello2b"}]
```

And the latter one is clearly incorrect.

**Comment by simster7** [comment]
The definition is correct. `ParallelSteps` has one field called `Steps` which is a list of `Steps`. It's just that in our `yaml` definitions we don't explicitly mention steps. So, your examples are actually equivalent:

`- steps: - name: step1` == `- - name: step1`

Do you know of a way for Swagger to signify anonymous fields?

**Comment by vilmosnagy** [comment]
@simster7 According to my understanding the `spec.template.steps` field should contain an array of arrays, not an array of objects with one field.

I tried to generate a json schema from the swagger definition, and validate my `workflow.yml`s to that json schema.

Aaand I think the Argo don't accept the workflows where I tried the latter one, see:

```yml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: no-such-template
spec:
  arguments:
    parameters:
      - {name: current-date, value: '20200219'}
  entrypoint: steps-with-reference
  volumes: []
  templates:
    - name: steps-with-reference
      steps:
        - - template: echo-hello-world
            name: echo-hello-world
    - name: echo-hello-world
      script:
        image: alpine
        command: ["sh", "-e"]
        source: |
          echo "hello world"
```

^-- This workflow just runs fine. But if I try to add the internal `steps` to the workflow, it fails:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: no-such-template
spec:
  arguments:
    parameters:
      - {name: current-date, value: '20200219'}
  entrypoint: steps-with-reference
  volumes: []
  templates:
    - name: steps-with-reference
      steps:
        - steps:
          - template: echo-hello-world
            name: echo-hello-world
    - name: echo-hello-world
      script:
        image: alpine
        command: ["sh", "-e"]
        source: |
          echo "hello world"
```

The error argo gives is:

```
[vilmosnagy@vnagy-dell psi-files]$ argo submit dag-and-steps-workflow.yml -w
2020/03/11 09:38:40 Failed to parse workflow: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field Template.spec.templates.steps of type []map[string]interface {}
```

**Comment by simster7** [comment]
Hi @vilmosnagy. `template.steps` is actually an array of objects with one field. `template.steps` is an array of object `ParallelSteps` which contains only one field: an array of object `WorkflowStep`. You can see so in our type definitions here:

`Steps` (which is `spec.template.steps`) is a list of object `ParallelSteps`:
https://github.com/argoproj/argo/blob/20d6e27bdf11389f23b2efe1be4ef737f333221d/pkg/apis/workflow/v1alpha1/workflow_types.go#L370

`ParallelSteps` (which is the anonymous field that you create when you use a list of lists `- -`) contains only one field called `Steps`, which is a list of type `WorkflowStep`:
https://github.com/argoproj/argo/blob/20d6e27bdf11389f23b2efe1be4ef737f333221d/pkg/apis/workflow/v1alpha1/workflow_types.go#L288-L290

You can see that this field does not contain a `json` tag, which is makes it anonymous. (If we're going to be pedantic, the tag should really be `json:",inline"` to explicitly mark it anonymous.)

My example really should have been: `- - name: step1` is equivalent to`- parallelSteps: - name: step1`. However, our JSON unmarshaller considers `parallelSteps` to be anonymous and inlines it automatically, so adding the field name will break the unmarshaller.

Regardless, our swagger files are generated automatically from our types anyway, so if this were actually a bug it should be taken with the code generator.

**Comment by vilmosnagy** [comment]
@simster7 Oookay. 

Long story short: I try to create an Intellij plugin which helps me working with workflow definitions. See the first baby steps here: https://gitlab.com/vilmosnagy/argo-intellij-plugin

I'm working with Argo for a couple of weeks now, and our workflows are defined in multiple template and yaml files, and each of those YAML files are a few thousand lines long. To be honest, it's a pain in the ass to work with these YAML files without any IDE support.

My plans include renaming, semantic-checking (are all the parameters defined for a template?), go to definition, and so on.

A nice first step would be(were) to provide autocompletion and syntactic checks - which is pretty easy if there's an available jsonschema for the YAML file. And I'm able to generate a jsonschema from an openapi (swagger) definition with the [openapi2jsonschema](https://github.com/garethr/openapi2jsonschema) tool. But your openapi definition does not represent the valid workflow definitions in the YAML format :'(

So my question is: are you willing to provide a jsonschema/openapi definition, which we can use in IntelliJ? If yes, can I help? How?

Thanks for your replies,
Regards,
Vilmos

**Comment by simster7** [comment]
Hi @vilmosnagy, thanks for sharing your use case! We would definitely appreciate your work on an IntelliJ plugin.

It seems like the issue here is that `ParallelSteps` is unnamed in our YAML, but not on our Open API spec. To solve this problem perhaps we should use the answer on this SO question: https://stackoverflow.com/questions/37975358/how-to-define-swagger-property-that-is-an-unknown-name

Perhaps something like this:

```
    "io.argoproj.workflow.v1alpha1.ParallelSteps": {
      "type": "object",
      "additionalProperties": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/io.argoproj.workflow.v1alpha1.WorkflowStep"
        },
        "minProperties": 1,
        "maxProperties": 1
    }
```

Could you try this to see if it would help? I have no experience working with Open API.

**Comment by simster7** [comment]
A ticket for this issue has been opened in #2454. Please keep the discussion there.

**Pull request closed without merging**
