### PR TITLE
fix: Fix Resource Deletion Bug

### PR DESCRIPTION
**Pull request by zhujl1991**
Fix https://github.com/argoproj/argo/issues/2078

Test:
Tested on minikube with the yaml mentioned [here](https://github.com/argoproj/argo/issues/2078#issuecomment-579407628). Manually delete the `Job` resource. Then `kubectl get wf zjl-k8s-jobs -o yaml` and the output is as expected:
```
......
  status:
    finishedAt: "2020-01-29T04:28:48Z"
    message: Resource Job.batch/pi-job-gsvvn in namespace default has been deleted
      somehow.
    nodes:
      zjl-k8s-jobs:
        displayName: zjl-k8s-jobs
        finishedAt: "2020-01-29T04:28:48Z"
        id: zjl-k8s-jobs
        message: Resource Job.batch/pi-job-gsvvn in namespace default has been deleted
          somehow.
        name: zjl-k8s-jobs
        phase: Failed
        startedAt: "2020-01-29T04:28:36Z"
        templateName: pi-tmpl
        type: Pod
    phase: Failed
    startedAt: "2020-01-29T04:28:36Z"
......
```

### CODE REVIEW

**Comment by zhujl1991** [comment]
@simster7 @jessesuen @alexec I don't have permission to https://hub.docker.com/r/argoproj/argoexec/tags?page=1 . So I'm not able to test the PR. Any suggestions about how to test this?

**Comment by simster7** [comment]
`make start` will build and deploy images locally

**Comment by zhujl1991** [comment]
> `make start` will build and deploy images locally

```
# Get UI dependencies
yarn --cwd ui install --frozen-lockfile --ignore-optional --non-interactive
make: yarn: No such file or directory
make: *** [ui/node_modules] Error 1
```
@simster7 I got this error when I ran `make start`.

**Comment by simster7** [comment]
Need to install [`yarn`](https://yarnpkg.com/)

**Comment by zhujl1991** [comment]
> Need to install [`yarn`](https://yarnpkg.com/)

```
# Get UI dependencies
yarn --cwd ui install --frozen-lockfile --ignore-optional --non-interactive
Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]
  1. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]

While running --cwd ui install --frozen-lockfile --ignore-optional --non-interactive
make: *** [ui/node_modules] Error 1
```

@simster7 Looks like it's not compatible with the latest `yarn?

**Comment by alexec** [comment]
> yarn --cwd ui instal

try just the above

**Comment by zhujl1991** [comment]
> yarn --cwd ui instal

@alexec 
```
# Get UI dependencies
# yarn --cwd ui install --frozen-lockfile --ignore-optional --non-interactive
yarn --cwd ui install
Ambiguous Syntax Error: Cannot find who to pick amongst the following alternatives:

  0. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]
  1. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--cache-folder #0]

While running --cwd ui install
```

**Comment by alexec** [comment]
ops - you'll need to edit the Makefile - can you tell me which version of yarn you are using?

```
yarn --version
```

**Comment by zhujl1991** [comment]
> ```
> yarn --version
> ```

2.0.0-rc.27

**Comment by alexec** [comment]
What happens if you use a production version of Yarn rather than a pre-release? I'm using v1.19.1

**Comment by zhujl1991** [comment]
image

`make start` still doesn't work for me because of this. Look like the image pull is failed. Are we making a dummy docker hub so that the image can be pulled locally? Can you give me some instructions to debug this? I can see the image has been built successfully by `docker image ls`. Thanks.

@simster7 @alexec @jessesuen

**Comment by alexec** [comment]
I don't know this code very well and can't give valuable feedback. I think either @sarabala1979 or @jessesuen would be best placed to review.

**Pull request merged**
