### PR TITLE
fix: kubectl deploy of manifests

### PR DESCRIPTION
**Pull request by MrFreezeex**
Signed-off-by: Arthur Outhenin-Chalandre <arthur@cri.epita.fr>

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [X] I've signed the CLA and required builds are green. 

This PR fixes the deploy with the version of kustomize included in kubectl (`kubectl apply -k` for instance). For some reasons, you can't apply directories with resources in kubectl, but you can with the kustomize binary.

### CODE REVIEW

**Comment by AnesBenmerzoug** [comment]
That happens because the version of Kustomize bundled with Kubectl is an older version. 
In newer versions, starting from [v3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0), **bases** was deprecated in favor of putting all resources and bases under  **resources**.

**Comment by MrFreezeex** [comment]
> That happens because the version of Kustomize bundled with Kubectl is an older version.
> In newer versions, starting from [v3.2.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/v3.2.0), **bases** was deprecated in favor of putting all resources and bases under **resources**.

Thanks, I didn't know that.

So basically, do argo wants to support the older (and deprecated way) that works with kubectl or juste be compatible with newer versions of kustomize ?

**Comment by simster7** [comment]
> So basically, do argo wants to support the older (and deprecated) way that works with kubectl or juste be compatible with newer versions of kustomize ?

We plan on using 3.2+. In theory, you shouldn't need to use kustomize at all, since the rendered manifests can be found under the /manifests folder

Thanks for your suggestion though! I'll be closing this

**Comment by MrFreezeex** [comment]
> We plan on using 3.2+. In theory, you shouldn't need to use kustomize at all, since the rendered manifests can be found under the /manifests folder

In fact I reference the kustomization file directly in my deployment (https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#resources-1).

If this is not supported by argo, I will use the kustomize binary directly... Maybe an issue can be opened to remove all the directories in the kustomization file ?

**Pull request closed without merging**
