### PR TITLE
ci: Changed tagging and amend multi-arch manifest

### LINKED ISSUE #2080: Argo Workflow for ARM?
# Summary

Could the argo team create official images for ARM (armv7/arm64)?

There are various rogue docker images of say argo-cd for ARM by community members but nothing really official. Would be nice to truly support ARM.

# Motivation

ARM is extremely popular, even in the datacenter, and I would like to be able to use Argo in an multi-architecture cluster.

# Proposal

Change build infrastructure to build both amd64 and arm variants.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by dgiebert**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Hopefully finally closes #2080

### CODE REVIEW

**Comment by dgiebert** [comment]
Whats the matter with the Semantic Pull Request ? :sweat:

**Comment by alexec** [comment]
> Whats the matter with the Semantic Pull Request ? 😓

If you only have a single commit, then Github uses that, instead of the PR title, as the merge message. You can fix by pushing an empty commit, but don't bother. I'll just edit it when I merge.

**Comment by alexec** [comment]
Builds now passing on master: did you want to check it? 

https://github.com/argoproj/argo/actions/runs/224163851

**Comment by dgiebert** [comment]
Did not work as expected:
- https://hub.docker.com/layers/argoproj/argoexec/latest/images/sha256-310980f0aba339d5a7b132304b61553d17116c86dafcf54ac0e5ccab729ee0ea

Let me check why it did only push the windows one

**Pull request merged**
