### PR TITLE
fix: Revert "chore: try out pre-pushing linux/amd64 images and updating ma… Fixes #4216

### LINKED ISSUE #4216: v2.11.1: error pulling image configuration: unknown blob
## Summary 

```
$ docker pull argoproj/argoexec:v2.11.1
v2.11.1: Pulling from argoproj/argoexec
54fec2fa59d0: Pulling fs layer
50e5b13654ba: Pulling fs layer
a13edb6ed3bd: Pulling fs layer
51bf6024f7b7: Waiting
be2f17b937f9: Waiting
6ff34160bd07: Waiting
6bddf1caf319: Waiting
61edb096a952: Waiting
332c15a1eb3f: Waiting
b596047ae0d6: Waiting
error pulling image configuration: unknown blob
```

## Diagnostics

What Kubernetes provider are you using?  N/A

What version of Argo Workflows are you running? v2.11.1

Caused by #4111?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
…nifest later (#4127)"

This reverts commit c8eed1f23adcdb9dfd99c81e2ba1a053ab27d558.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] ~~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
* [x] My builds are green. Try syncing with master if they are not. 

Fixes #4216

### CODE REVIEW

**Review by simster7 — APPROVED** [review]

**Comment by lippertmarkus** [comment]
`docker pull argoproj/argoexec:latest` worked fine so reverting this change on the master branch is the wrong place IMO. For v2.11.1 you need to have a look at the `v2.11.1` branch where changes from https://github.com/argoproj/argo/pull/4127 don't even exist.

**Comment by alexec** [comment]
@lippertmarkus any thoughts to what is causing this problem?

**Comment by alexec** [comment]
`38b63008 chore: use build matrix and cache (#4111)`

**Comment by lippertmarkus** [comment]
Maybe I miss something but `38b63008 chore: use build matrix and cache (#4111)` was the last commit on `release-v2.11` which seems to have the problem. But with this PR you just reverted c8eed1f23adcdb9dfd99c81e2ba1a053ab27d558 from #4127 which doesn't seem to have the problem as `docker pull argoproj/argoexec:latest` (which comes from the master branch) worked fine before the revert.

**Comment by alexec** [comment]
This is a bit on a challenge to fix. We must run the workflows to prove any fix and we can only do that on master. So we must test out fixes on master. 

@lippertmarkus could I ask you to raise a PR to revert #4111 ASAP please?

**Comment by alexec** [comment]
Basically - lets get it working on master - and then we can copy the files to v2.11

**Comment by alexec** [comment]
It's going to really tedious to fix this.

**Comment by alexec** [comment]
I take this back, better solution - revert v2.11 to know working version, i.e v2.11.1.

**Comment by lippertmarkus** [comment]
but it already worked on master...

**Comment by lippertmarkus** [comment]
Creating a new tag now should be enough, shouldn't it?

**Pull request merged**
