### PR TITLE
docs: Formatting workflow template

### PR DESCRIPTION
**Pull request by max-sixty**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
~* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~
* [ ] My builds are green. Try syncing with master if they are not. 
~* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).~

Note the weird formatting with the existing md:
image

### CODE REVIEW

**Comment by simster7** [comment]
@max-sixty Looks like you need to sign the CLA

**Comment by max-sixty** [comment]
@simster7 I'm checking my end re the CLA; I recently started a new job so forgive the delay.

Somewhat separately, one aspect of the documentation I find missing is a single place to see options for workflow definitions.

It's this WorkflowTemplate page which states:

> Whenever you define a `Workflow`, you must define at least one (but usually more than one) `template` to run. This `template` can be of type `container`, `script`, `dag`, `steps`, `resource`, or `suspend` and can be referenced by an `entrypoint` or by other `dag`, and `step` templates."

...which I found very helpful context for defining what could go in a template field, and lacking from the Workflow documentation itself. 
I find myself Ctrl-F the [go code](https://github.com/argoproj/argo/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go), despite not really knowing go.

What are your thoughts about a yaml page with all the possible options for workflows? Or some other form? The examples page is useful but very spread-out and lacking a summary by field, so it's difficult to see "these are the possible options for the template field", for example.

**Comment by simster7** [comment]
@max-sixty Have you taken a look at our [fields doc](https://github.com/argoproj/argo/blob/master/docs/fields.md#workflowspec)?

**Comment by max-sixty** [comment]
Another question (maybe there's a better forum for these) — what's the purpose of having both `Workflow` and `WorkflowTemplate`? IIUC they have the same fields; only the `kind` is different. Why not allow referencing any other `Workflow`, rather than having an additional type which enables referencing?

**Comment by max-sixty** [comment]
> @max-sixty Have you taken a look at our [fields doc](https://github.com/argoproj/argo/blob/master/docs/fields.md#workflowspec)?

This is perfect! Exactly what I had hoped for. Thank you for the pointer. 

And I see it's linked from the home page of the docs, so this is probably a user mistake rather than a docs mistake. 
Maybe if others hit this it could be added to the top bar; e.g. (`Overview | Getting Started | Examples | Field Definitions`)

**Comment by simster7** [comment]
> Another question (maybe there's a better forum for these) — what's the purpose of having both Workflow and WorkflowTemplate? IIUC they have the same fields; only the kind is different. Why not allow referencing any other Workflow, rather than having an additional type which enables referencing?

Have you taken a look at our [`WorkflowTemplate` doc](https://github.com/argoproj/argo/blob/master/docs/workflow-templates.md)? If you have and are looking for a more specific answer: `Workflows` are definitions and instances of a single `Workflow` "run", i.e. all information regarding that run is stored on the same object and that object can be deleted at any time. `WorkflowTemplates` are strictly definitions... not intended to store state and intended to be persisted. That is why we reference `WorkflowTemplates` as opposed to other `Workflows`

**Comment by max-sixty** [comment]
I appreciate the response. I'll use them more and come back if I still have questions. Thanks!

**Comment by simster7** [comment]
@max-sixty Were you able to figure out the CLA?

**Comment by max-sixty** [comment]
Still waiting — apologies. It's such a trivial change, so seems absurd on its face, but both sides care about it, it seems. Feel free to copy to another PR, or I'll let you know when it's resolved.

**Comment by alexec** [comment]
Could we give this a better title for the release notes please?

**Comment by max-sixty** [comment]
Yes. Unfortunately I still haven't heard back re the CLA. I expect I will eventually. Thanks for your understanding (and to the extent someone else wants to make a new PR, please don't stop on my account)

**Comment by alexec** [comment]
I think we can forgo CLA for a doc only change.

**Comment by jessesuen** [comment]
Looks like change got merged

**Pull request closed without merging**
