### PR TITLE
Add exports parameter for artifact sharing

### PR DESCRIPTION
**Pull request by dtaniwaki**
I don't know if this is the best solution but we can use `emptyDir` to collect artifacts from main containers. Using this feature, we can use the full features of Argo even with the kubelet executor. I actually wanted this required parameter of outputs but I left it optional to keep the compatibility.
Please tell me if we should make it a required parameter and remove unnecessary executor methods of `CopyFile` and `GetFileContents `. Or we can do it in another PR.

I think this feature solves the problem of #1003 and #1021.

### CODE REVIEW

**Comment by booninite** [comment]
super duper +1, our org at IBM wants to leverage containerd and argo but this is blocking us :)

**Comment by dtaniwaki** [comment]
I understand your thought. I think the 1st reason really makes sense to me. I think that's the best way to do it. Or, we can improve kubelet/kubernetes API to use `docker cp` like command internally. There's [a related issue in Kubernetes repo](https://github.com/kubernetes/kubectl/issues/454).

> There is a technique we have used in the past (argo v1), where we mapped in the executor static binary to the main container, then invoked the user defined command/args of the container, which allowed us to gain control of the post-processing phase while we still had direct access to the main container's filesystem.

I don't know if users want to put the binary in their containers and let Argo do something there because containers should be isolated even if it runs as a part of a workflow system.

So, for the time being, should we throw unsupported-feature exceptions in `CopyFile` and `GetFileContents` of the kubelet, and coming k8sapi, executors so users don't be confused with the system error?

**Comment by dtaniwaki** [comment]
By the way, the [k8sapi executor](https://github.com/argoproj/argo/pull/1010) solves some of the  problems about artifact sharing because it doesn't use `exec` to print logs. I'd like to make them throw unsupported feature exceptions accordingly.

**Comment by dtaniwaki** [comment]
@jessesuen I remember we discussed how this feature should be implemented in offline and you had the idea of utilizing `volumeMounts` of the main container to automatically mount the volumes in the corresponded wait container. If you're too busy to implement it, I will do it as I need it in my projects ASAP.

**Comment by dtaniwaki** [comment]
I'm closing this PR as @jessesuen is working on a better solution explained in https://github.com/argoproj/argo/issues/1003#issuecomment-452947976.

**Pull request closed without merging**
