### PR TITLE
fix(module): update import to to /v2

### PR DESCRIPTION
**Pull request by tcolgate**
This fixes importing argo as a go module. I'm guessing there is a strong
chance that you wont want to fix this, but I thought I'd raise the PR
anyway. The e2e tests fail at present, I'm not sure why.

### CODE REVIEW

**Comment by tcolgate** [comment]
amusingly enough, I had a port forward open to my ci Instance and accidentally launched all the e2e test jobs on there :bomb:

**Comment by alexec** [comment]
@tcolgate let me see if I understand - we cannot import as go module without this change?

**Comment by tcolgate** [comment]
Not quite, you can't be imported with a regular version import, people have to import a specific commit. That works fine, but they literally need the commit id, can't use the tag.
I am really not sure to want extent this change is a good idea. If you want people to trivially import your code as a package, then maybe it is worth it.
Absolutely don't merge this as is though, I've no idea what it'll break and don't think it even vaguely works.

**Comment by alexec** [comment]
I think we would want this. How to get it to work?

**Pull request closed without merging**
