### PR TITLE
chore: Remove extreneous config from quick-start

### PR DESCRIPTION
**Pull request by simster7**
Minor

### CODE REVIEW

**Comment by simster7** [comment]
@alexec I simply removed them from quick-start and ran `make manifests`. Seems like `make manifests` also updates `tests/`:

```
make manifests
# GIT_TAG=, GIT_BRANCH=man, GIT_TREE_STATE=dirty, VERSION=man, DEV_IMAGE=true
...
# Create Postgres e2e manifests
kustomize build test/e2e/manifests/postgres | ./hack/auto-gen-msg.sh > test/e2e/manifests/postgres.yaml
# Create MySQL e2e manifests
kustomize build test/e2e/manifests/mysql | ./hack/auto-gen-msg.sh > test/e2e/manifests/mysql.yaml
# Create no DB e2e manifests
kustomize build test/e2e/manifests/no-db | ./hack/auto-gen-msg.sh > test/e2e/manifests/no-db.yaml
```

I also ran the relevant tests to make sure they worked before I opened this PR.

**Comment by alexec** [comment]
> I also ran the relevant tests to make sure they worked before I opened this PR.

Do you want to @mention the author and find out?

**Comment by simster7** [comment]
@jamhed Are these configs necessary for the tests in #2385?

**Comment by jamhed** [comment]
@simster7, yes, they are necessary, without limits argo watcher pod can't be submitted if we have resourcequota enabled for namespace, I copied values from existing examples.

**Comment by simster7** [comment]
Alright, thanks. Will close this for now.

**Comment by simster7** [comment]
I'm reconsidering this... @alexec currently we use the same set of templates for quick-start and for testing, but this change only needs to be in our testing manifests. I don't think that this should be in our quick-start manifests because it introduces behavior that is not desired by default.

What do you think about decoupling the quick-start manifests and the testing manifests? If we do so, we can remove this executor config from the quick-start manifests and keep it in the testing manifests.

**Comment by alexec** [comment]
> I'm reconsidering this... @alexec currently we use the same set of templates for quick-start and for testing, but this change only needs to be in our testing manifests. I don't think that this should be in our quick-start manifests because it introduces behavior that is not desired by default.
> 
> What do you think about decoupling the quick-start manifests and the testing manifests? If we do so, we can remove this executor config from the quick-start manifests and keep it in the testing manifests.

I was keen to keep them closely related. Otherwise, we never test the manifests (both install.yaml and quick-starts) are correct. I'd prefer we only kustomize the test manifests and there are scripts for that.

**Comment by alexec** [comment]
This will be fixed by https://github.com/argoproj/argo/pull/2464.

**Comment by simster7** [comment]
Closing

**Pull request closed without merging**
