### PR TITLE
feat(dependencies): Update k8s dependencies to 19.3. Fixes #4425

### LINKED ISSUE #4425: Update k8s.io/api, k8s.io/apimachinery and k8s.io/client-go
# Summary

Update go dependencies to stay up to date. 

# Use Cases

I have had issues trying to updated the argo version for Kubeflow pipelines to argo 2.11(currently are on 2.7) and updating the underlying dependencies for argo would make the update simpler. I understand this might not be a good enough reason to update the dependencies for argo it self though. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by NikeNano**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
This seems like something we want to target for v3. As a result we’d also need to update Argo events.

**Comment by NikeNano** [comment]
> This seems like something we want to target for v3. As a result we’d also need to update Argo events.

ok, I have started the work for workflows and will take a look at evens when I succeed :). When is the target for v3 @alexec ?

**Comment by animeshsingh** [comment]
@NikeNano @alexec when is v3 targeted? We also have a blocker dependency on moving to k8s client higher version asap.

**Comment by NikeNano** [comment]
> @NikeNano when is v3 targeted? We also have a blocker dependency on moving to k8s client higher version asap.

Dont know, I try to look at this form time to time, but a lot of small things that needs to be updated @animeshsingh

**Comment by alexec** [comment]
v3 is target end of January. We should get this PR into that release.

**Comment by alexec** [comment]
See #4810

**Pull request closed without merging**
